//! Configuration state packet definitions.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::{Decode, Encode, EncodedSize, packet};
use basalt_types::Decode as _;
use basalt_types::{NbtCompound, Uuid};

use crate::error::{Error, Result};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x02)]
pub struct ServerboundConfigurationCustomPayload {
    pub channel: String,
    #[field(rest)]
    pub data: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x03)]
pub struct ServerboundConfigurationFinishConfiguration;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x04)]
pub struct ServerboundConfigurationKeepAlive {
    pub keep_alive_id: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x05)]
pub struct ServerboundConfigurationPong {
    pub id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x06)]
pub struct ServerboundConfigurationResourcePackReceive {
    pub uuid: Uuid,
    #[field(varint)]
    pub result: i32,
}

// -- Clientbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x01)]
pub struct ClientboundConfigurationCustomPayload {
    pub channel: String,
    #[field(rest)]
    pub data: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x02)]
pub struct ClientboundConfigurationDisconnect {
    pub reason: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0c)]
pub struct ClientboundConfigurationFeatureFlags {
    #[field(length = "varint")]
    pub features: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x03)]
pub struct ClientboundConfigurationFinishConfiguration;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x04)]
pub struct ClientboundConfigurationKeepAlive {
    pub keep_alive_id: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x05)]
pub struct ClientboundConfigurationPing {
    pub id: i32,
}

/// Inline data structure used by [`ClientboundConfigurationRegistryData`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundConfigurationRegistryDataEntries {
    pub key: String,
    #[field(optional)]
    pub value: Option<NbtCompound>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x07)]
pub struct ClientboundConfigurationRegistryData {
    pub id: String,
    #[field(length = "varint")]
    pub entries: Vec<ClientboundConfigurationRegistryDataEntries>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x06)]
pub struct ClientboundConfigurationResetChat;

/// Inline data structure used by [`ClientboundConfigurationTags`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundConfigurationTagsTags {
    pub tag_type: String,
    pub tags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0d)]
pub struct ClientboundConfigurationTags {
    #[field(length = "varint")]
    pub tags: Vec<ClientboundConfigurationTagsTags>,
}

/// serverbound packets in the Configuration state.
#[derive(Debug, Clone, PartialEq)]
pub enum ServerboundConfigurationPacket {
    CustomPayload(ServerboundConfigurationCustomPayload),
    FinishConfiguration(ServerboundConfigurationFinishConfiguration),
    KeepAlive(ServerboundConfigurationKeepAlive),
    Pong(ServerboundConfigurationPong),
    ResourcePackReceive(ServerboundConfigurationResourcePackReceive),
}

impl ServerboundConfigurationPacket {
    /// Decodes a packet from its ID and payload.
    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {
        match id {
            ServerboundConfigurationCustomPayload::PACKET_ID => Ok(Self::CustomPayload(
                ServerboundConfigurationCustomPayload::decode(buf)?,
            )),
            ServerboundConfigurationFinishConfiguration::PACKET_ID => {
                Ok(Self::FinishConfiguration(
                    ServerboundConfigurationFinishConfiguration::decode(buf)?,
                ))
            }
            ServerboundConfigurationKeepAlive::PACKET_ID => Ok(Self::KeepAlive(
                ServerboundConfigurationKeepAlive::decode(buf)?,
            )),
            ServerboundConfigurationPong::PACKET_ID => {
                Ok(Self::Pong(ServerboundConfigurationPong::decode(buf)?))
            }
            ServerboundConfigurationResourcePackReceive::PACKET_ID => {
                Ok(Self::ResourcePackReceive(
                    ServerboundConfigurationResourcePackReceive::decode(buf)?,
                ))
            }
            _ => Err(Error::UnknownPacket {
                id,
                state: "configuration",
            }),
        }
    }
}

/// clientbound packets in the Configuration state.
#[derive(Debug, Clone, PartialEq)]
pub enum ClientboundConfigurationPacket {
    CustomPayload(ClientboundConfigurationCustomPayload),
    Disconnect(ClientboundConfigurationDisconnect),
    FeatureFlags(ClientboundConfigurationFeatureFlags),
    FinishConfiguration(ClientboundConfigurationFinishConfiguration),
    KeepAlive(ClientboundConfigurationKeepAlive),
    Ping(ClientboundConfigurationPing),
    RegistryData(ClientboundConfigurationRegistryData),
    ResetChat(ClientboundConfigurationResetChat),
    Tags(ClientboundConfigurationTags),
}

impl ClientboundConfigurationPacket {
    /// Decodes a packet from its ID and payload.
    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {
        match id {
            ClientboundConfigurationCustomPayload::PACKET_ID => Ok(Self::CustomPayload(
                ClientboundConfigurationCustomPayload::decode(buf)?,
            )),
            ClientboundConfigurationDisconnect::PACKET_ID => Ok(Self::Disconnect(
                ClientboundConfigurationDisconnect::decode(buf)?,
            )),
            ClientboundConfigurationFeatureFlags::PACKET_ID => Ok(Self::FeatureFlags(
                ClientboundConfigurationFeatureFlags::decode(buf)?,
            )),
            ClientboundConfigurationFinishConfiguration::PACKET_ID => {
                Ok(Self::FinishConfiguration(
                    ClientboundConfigurationFinishConfiguration::decode(buf)?,
                ))
            }
            ClientboundConfigurationKeepAlive::PACKET_ID => Ok(Self::KeepAlive(
                ClientboundConfigurationKeepAlive::decode(buf)?,
            )),
            ClientboundConfigurationPing::PACKET_ID => {
                Ok(Self::Ping(ClientboundConfigurationPing::decode(buf)?))
            }
            ClientboundConfigurationRegistryData::PACKET_ID => Ok(Self::RegistryData(
                ClientboundConfigurationRegistryData::decode(buf)?,
            )),
            ClientboundConfigurationResetChat::PACKET_ID => Ok(Self::ResetChat(
                ClientboundConfigurationResetChat::decode(buf)?,
            )),
            ClientboundConfigurationTags::PACKET_ID => {
                Ok(Self::Tags(ClientboundConfigurationTags::decode(buf)?))
            }
            _ => Err(Error::UnknownPacket {
                id,
                state: "configuration",
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use basalt_types::{Encode as _, EncodedSize as _};

    #[test]
    fn serverbound_packet_ids() {
        assert_eq!(ServerboundConfigurationCustomPayload::PACKET_ID, 0x02);
        assert_eq!(ServerboundConfigurationFinishConfiguration::PACKET_ID, 0x03);
        assert_eq!(ServerboundConfigurationKeepAlive::PACKET_ID, 0x04);
        assert_eq!(ServerboundConfigurationPong::PACKET_ID, 0x05);
        assert_eq!(ServerboundConfigurationResourcePackReceive::PACKET_ID, 0x06);
    }

    #[test]
    fn unknown_serverbound_id() {
        let mut cursor: &[u8] = &[];
        assert!(ServerboundConfigurationPacket::decode_by_id(0xFF, &mut cursor).is_err());
    }

    #[test]
    fn clientbound_packet_ids() {
        assert_eq!(ClientboundConfigurationCustomPayload::PACKET_ID, 0x01);
        assert_eq!(ClientboundConfigurationDisconnect::PACKET_ID, 0x02);
        assert_eq!(ClientboundConfigurationFeatureFlags::PACKET_ID, 0x0c);
        assert_eq!(ClientboundConfigurationFinishConfiguration::PACKET_ID, 0x03);
        assert_eq!(ClientboundConfigurationKeepAlive::PACKET_ID, 0x04);
        assert_eq!(ClientboundConfigurationPing::PACKET_ID, 0x05);
        assert_eq!(ClientboundConfigurationRegistryData::PACKET_ID, 0x07);
        assert_eq!(ClientboundConfigurationResetChat::PACKET_ID, 0x06);
        assert_eq!(ClientboundConfigurationTags::PACKET_ID, 0x0d);
    }

    #[test]
    fn unknown_clientbound_id() {
        let mut cursor: &[u8] = &[];
        assert!(ClientboundConfigurationPacket::decode_by_id(0xFF, &mut cursor).is_err());
    }

    #[test]
    fn serverbound_configuration_custom_payload_roundtrip() {
        let original = ServerboundConfigurationCustomPayload::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundConfigurationCustomPayload::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_configuration_finish_configuration_roundtrip() {
        let original = ServerboundConfigurationFinishConfiguration;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundConfigurationFinishConfiguration::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_configuration_keep_alive_roundtrip() {
        let original = ServerboundConfigurationKeepAlive::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundConfigurationKeepAlive::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_configuration_pong_roundtrip() {
        let original = ServerboundConfigurationPong::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundConfigurationPong::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_configuration_resource_pack_receive_roundtrip() {
        let original = ServerboundConfigurationResourcePackReceive::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundConfigurationResourcePackReceive::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_custom_payload_roundtrip() {
        let original = ClientboundConfigurationCustomPayload::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationCustomPayload::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_disconnect_roundtrip() {
        let original = ClientboundConfigurationDisconnect::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationDisconnect::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_feature_flags_roundtrip() {
        let original = ClientboundConfigurationFeatureFlags::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationFeatureFlags::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_finish_configuration_roundtrip() {
        let original = ClientboundConfigurationFinishConfiguration;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationFinishConfiguration::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_keep_alive_roundtrip() {
        let original = ClientboundConfigurationKeepAlive::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationKeepAlive::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_ping_roundtrip() {
        let original = ClientboundConfigurationPing::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationPing::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_registry_data_roundtrip() {
        let original = ClientboundConfigurationRegistryData::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationRegistryData::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_reset_chat_roundtrip() {
        let original = ClientboundConfigurationResetChat;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationResetChat::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_configuration_tags_roundtrip() {
        let original = ClientboundConfigurationTags::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundConfigurationTags::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }
}
