//! Login state packet definitions.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::{Decode, Encode, EncodedSize, packet};
use basalt_types::Decode as _;
use basalt_types::Uuid;

use crate::error::{Error, Result};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x01)]
pub struct ServerboundLoginEncryptionBegin {
    #[field(length = "varint")]
    pub shared_secret: Vec<u8>,
    #[field(length = "varint")]
    pub verify_token: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x03)]
pub struct ServerboundLoginLoginAcknowledged;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x02)]
pub struct ServerboundLoginLoginPluginResponse {
    #[field(varint)]
    pub message_id: i32,
    #[field(optional)]
    pub data: Option<Vec<u8>>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x00)]
pub struct ServerboundLoginLoginStart {
    pub username: String,
    pub player_uuid: Uuid,
}

// -- Clientbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x03)]
pub struct ClientboundLoginCompress {
    #[field(varint)]
    pub threshold: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x00)]
pub struct ClientboundLoginDisconnect {
    pub reason: String,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x01)]
pub struct ClientboundLoginEncryptionBegin {
    pub server_id: String,
    #[field(length = "varint")]
    pub public_key: Vec<u8>,
    #[field(length = "varint")]
    pub verify_token: Vec<u8>,
    pub should_authenticate: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x04)]
pub struct ClientboundLoginLoginPluginRequest {
    #[field(varint)]
    pub message_id: i32,
    pub channel: String,
    #[field(rest)]
    pub data: Vec<u8>,
}

/// Inline data structure used by [`ClientboundLoginSuccess`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundLoginSuccessProperties {
    pub name: String,
    pub value: String,
    #[field(optional)]
    pub signature: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x02)]
pub struct ClientboundLoginSuccess {
    pub uuid: Uuid,
    pub username: String,
    #[field(length = "varint")]
    pub properties: Vec<ClientboundLoginSuccessProperties>,
}

/// serverbound packets in the Login state.
#[derive(Debug, Clone, PartialEq)]
pub enum ServerboundLoginPacket {
    EncryptionBegin(ServerboundLoginEncryptionBegin),
    LoginAcknowledged(ServerboundLoginLoginAcknowledged),
    LoginPluginResponse(ServerboundLoginLoginPluginResponse),
    LoginStart(ServerboundLoginLoginStart),
}

impl ServerboundLoginPacket {
    /// Decodes a packet from its ID and payload.
    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {
        match id {
            ServerboundLoginEncryptionBegin::PACKET_ID => Ok(Self::EncryptionBegin(
                ServerboundLoginEncryptionBegin::decode(buf)?,
            )),
            ServerboundLoginLoginAcknowledged::PACKET_ID => Ok(Self::LoginAcknowledged(
                ServerboundLoginLoginAcknowledged::decode(buf)?,
            )),
            ServerboundLoginLoginPluginResponse::PACKET_ID => Ok(Self::LoginPluginResponse(
                ServerboundLoginLoginPluginResponse::decode(buf)?,
            )),
            ServerboundLoginLoginStart::PACKET_ID => {
                Ok(Self::LoginStart(ServerboundLoginLoginStart::decode(buf)?))
            }
            _ => Err(Error::UnknownPacket { id, state: "login" }),
        }
    }
}

/// clientbound packets in the Login state.
#[derive(Debug, Clone, PartialEq)]
pub enum ClientboundLoginPacket {
    Compress(ClientboundLoginCompress),
    Disconnect(ClientboundLoginDisconnect),
    EncryptionBegin(ClientboundLoginEncryptionBegin),
    LoginPluginRequest(ClientboundLoginLoginPluginRequest),
    Success(ClientboundLoginSuccess),
}

impl ClientboundLoginPacket {
    /// Decodes a packet from its ID and payload.
    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {
        match id {
            ClientboundLoginCompress::PACKET_ID => {
                Ok(Self::Compress(ClientboundLoginCompress::decode(buf)?))
            }
            ClientboundLoginDisconnect::PACKET_ID => {
                Ok(Self::Disconnect(ClientboundLoginDisconnect::decode(buf)?))
            }
            ClientboundLoginEncryptionBegin::PACKET_ID => Ok(Self::EncryptionBegin(
                ClientboundLoginEncryptionBegin::decode(buf)?,
            )),
            ClientboundLoginLoginPluginRequest::PACKET_ID => Ok(Self::LoginPluginRequest(
                ClientboundLoginLoginPluginRequest::decode(buf)?,
            )),
            ClientboundLoginSuccess::PACKET_ID => {
                Ok(Self::Success(ClientboundLoginSuccess::decode(buf)?))
            }
            _ => Err(Error::UnknownPacket { id, state: "login" }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use basalt_types::{Encode as _, EncodedSize as _};

    #[test]
    fn serverbound_packet_ids() {
        assert_eq!(ServerboundLoginEncryptionBegin::PACKET_ID, 0x01);
        assert_eq!(ServerboundLoginLoginAcknowledged::PACKET_ID, 0x03);
        assert_eq!(ServerboundLoginLoginPluginResponse::PACKET_ID, 0x02);
        assert_eq!(ServerboundLoginLoginStart::PACKET_ID, 0x00);
    }

    #[test]
    fn unknown_serverbound_id() {
        let mut cursor: &[u8] = &[];
        assert!(ServerboundLoginPacket::decode_by_id(0xFF, &mut cursor).is_err());
    }

    #[test]
    fn clientbound_packet_ids() {
        assert_eq!(ClientboundLoginCompress::PACKET_ID, 0x03);
        assert_eq!(ClientboundLoginDisconnect::PACKET_ID, 0x00);
        assert_eq!(ClientboundLoginEncryptionBegin::PACKET_ID, 0x01);
        assert_eq!(ClientboundLoginLoginPluginRequest::PACKET_ID, 0x04);
        assert_eq!(ClientboundLoginSuccess::PACKET_ID, 0x02);
    }

    #[test]
    fn unknown_clientbound_id() {
        let mut cursor: &[u8] = &[];
        assert!(ClientboundLoginPacket::decode_by_id(0xFF, &mut cursor).is_err());
    }

    #[test]
    fn serverbound_login_encryption_begin_roundtrip() {
        let original = ServerboundLoginEncryptionBegin::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundLoginEncryptionBegin::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_login_login_acknowledged_roundtrip() {
        let original = ServerboundLoginLoginAcknowledged;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundLoginLoginAcknowledged::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_login_login_plugin_response_roundtrip() {
        let original = ServerboundLoginLoginPluginResponse::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundLoginLoginPluginResponse::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_login_login_start_roundtrip() {
        let original = ServerboundLoginLoginStart::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundLoginLoginStart::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_login_compress_roundtrip() {
        let original = ClientboundLoginCompress::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundLoginCompress::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_login_disconnect_roundtrip() {
        let original = ClientboundLoginDisconnect::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundLoginDisconnect::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_login_encryption_begin_roundtrip() {
        let original = ClientboundLoginEncryptionBegin::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundLoginEncryptionBegin::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_login_login_plugin_request_roundtrip() {
        let original = ClientboundLoginLoginPluginRequest::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundLoginLoginPluginRequest::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_login_success_roundtrip() {
        let original = ClientboundLoginSuccess::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundLoginSuccess::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }
}
