//! Minecraft packet definitions organized by connection state.
//!
//! Each submodule contains the packet structs for one connection state,
//! along with direction-specific enums (serverbound/clientbound) that
//! enable exhaustive pattern matching on received packets.
//!
//! Auto-generated by `cargo xt codegen`. Do not edit manually.

pub mod handshake;
pub mod login;
pub mod status;
