//! Status state packet definitions.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::packet;
use basalt_types::Decode as _;

use crate::error::{Error, Result};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x01)]
pub struct ServerboundStatusPing {
    pub time: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x00)]
pub struct ServerboundStatusPingStart;

// -- Clientbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x01)]
pub struct ClientboundStatusPing {
    pub time: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x00)]
pub struct ClientboundStatusServerInfo {
    pub response: String,
}

/// serverbound packets in the Status state.
#[derive(Debug, Clone, PartialEq)]
pub enum ServerboundStatusPacket {
    Ping(ServerboundStatusPing),
    PingStart(ServerboundStatusPingStart),
}

impl ServerboundStatusPacket {
    /// Decodes a packet from its ID and payload.
    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {
        match id {
            ServerboundStatusPing::PACKET_ID => Ok(Self::Ping(ServerboundStatusPing::decode(buf)?)),
            ServerboundStatusPingStart::PACKET_ID => {
                Ok(Self::PingStart(ServerboundStatusPingStart::decode(buf)?))
            }
            _ => Err(Error::UnknownPacket {
                id,
                state: "status",
            }),
        }
    }
}

/// clientbound packets in the Status state.
#[derive(Debug, Clone, PartialEq)]
pub enum ClientboundStatusPacket {
    Ping(ClientboundStatusPing),
    ServerInfo(ClientboundStatusServerInfo),
}

impl ClientboundStatusPacket {
    /// Decodes a packet from its ID and payload.
    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {
        match id {
            ClientboundStatusPing::PACKET_ID => Ok(Self::Ping(ClientboundStatusPing::decode(buf)?)),
            ClientboundStatusServerInfo::PACKET_ID => {
                Ok(Self::ServerInfo(ClientboundStatusServerInfo::decode(buf)?))
            }
            _ => Err(Error::UnknownPacket {
                id,
                state: "status",
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use basalt_types::{Encode as _, EncodedSize as _};

    #[test]
    fn serverbound_packet_ids() {
        assert_eq!(ServerboundStatusPing::PACKET_ID, 0x01);
        assert_eq!(ServerboundStatusPingStart::PACKET_ID, 0x00);
    }

    #[test]
    fn unknown_serverbound_id() {
        let mut cursor: &[u8] = &[];
        assert!(ServerboundStatusPacket::decode_by_id(0xFF, &mut cursor).is_err());
    }

    #[test]
    fn clientbound_packet_ids() {
        assert_eq!(ClientboundStatusPing::PACKET_ID, 0x01);
        assert_eq!(ClientboundStatusServerInfo::PACKET_ID, 0x00);
    }

    #[test]
    fn unknown_clientbound_id() {
        let mut cursor: &[u8] = &[];
        assert!(ClientboundStatusPacket::decode_by_id(0xFF, &mut cursor).is_err());
    }

    #[test]
    fn serverbound_status_ping_roundtrip() {
        let original = ServerboundStatusPing::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundStatusPing::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_status_ping_start_roundtrip() {
        let original = ServerboundStatusPingStart;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundStatusPingStart::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_status_ping_roundtrip() {
        let original = ClientboundStatusPing::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundStatusPing::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_status_server_info_roundtrip() {
        let original = ClientboundStatusServerInfo::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundStatusServerInfo::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }
}
