//! Rust source code generation from the `ProtocolType` IR.
//!
//! Turns `PacketDef` values (containing `ResolvedField` with `ProtocolType`)
//! into formatted Rust source code: packet structs, inline helper structs,
//! switch enums, direction dispatch enums, and complete state module files.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use serde_json::Value;

use crate::helpers::{short_variant_name, to_pascal_case};
use crate::registry::TypeRegistry;
use crate::types::{PacketDef, ProtocolType, ResolvedField, SwitchVariant};

/// Generates the `packets/mod.rs` file by scanning existing `.rs` files
/// and directories in the packets output directory.
pub(crate) fn generate_packets_mod(workspace_root: &Path, packets_dir: &str) -> String {
    let dir = workspace_root.join(packets_dir);
    let mut modules: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", dir.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().to_string_lossy().to_string();
            let file_type = entry.file_type().ok()?;
            if file_type.is_dir() {
                Some(name)
            } else if name.ends_with(".rs") && name != "mod.rs" {
                Some(name.strip_suffix(".rs").unwrap().to_string())
            } else {
                None
            }
        })
        .collect();
    modules.sort();

    let mut out = String::new();
    out.push_str("//! Minecraft packet definitions organized by connection state.\n");
    out.push_str("//!\n");
    out.push_str("//! Each submodule contains the packet structs for one connection state,\n");
    out.push_str("//! along with direction-specific enums (serverbound/clientbound) that\n");
    out.push_str("//! enable exhaustive pattern matching on received packets.\n");
    out.push_str("//!\n");
    out.push_str("//! Auto-generated by `cargo xt codegen`. Do not edit manually.\n\n");
    for module in &modules {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}

/// Generates a complete Rust module for one protocol state.
///
/// Creates a `TypeRegistry`, parses both directions, collects all type
/// imports, generates packet structs with inline helpers, and emits
/// direction dispatch enums with `decode_by_id`.
pub(crate) fn generate_state_module(
    state: &Value,
    module_name: &str,
    global_types: &Value,
) -> String {
    let mut output = String::new();
    let pascal_state = to_pascal_case(module_name);

    output.push_str(&format!("//! {pascal_state} state packet definitions.\n"));
    output.push_str("//!\n");
    output.push_str("//! Auto-generated by `cargo xt codegen` from minecraft-data.\n");
    output.push_str("//! Do not edit manually — changes will be overwritten.\n\n");

    let registry = TypeRegistry::new(&state["toServer"]["types"], global_types);
    let serverbound = registry.parse_direction(state, "toServer", "Serverbound", &pascal_state);

    let registry = TypeRegistry::new(&state["toClient"]["types"], global_types);
    let clientbound = registry.parse_direction(state, "toClient", "Clientbound", &pascal_state);

    let all_packets: Vec<&PacketDef> = serverbound.iter().chain(clientbound.iter()).collect();

    output.push_str(&generate_imports(&all_packets));
    output.push_str("use basalt_types::Decode as _;\n");
    output.push_str("\nuse crate::error::{Error, Result};\n\n");

    if !serverbound.is_empty() {
        output.push_str("// -- Serverbound packets --\n\n");
        for packet in &serverbound {
            output.push_str(&generate_packet_struct(packet));
            output.push('\n');
        }
    }

    if !clientbound.is_empty() {
        output.push_str("// -- Clientbound packets --\n\n");
        for packet in &clientbound {
            output.push_str(&generate_packet_struct(packet));
            output.push('\n');
        }
    }

    if !serverbound.is_empty() {
        output.push_str(&generate_direction_enum(
            &format!("Serverbound{pascal_state}Packet"),
            &serverbound,
            module_name,
            &pascal_state,
        ));
        output.push('\n');
    }

    if !clientbound.is_empty() {
        output.push_str(&generate_direction_enum(
            &format!("Clientbound{pascal_state}Packet"),
            &clientbound,
            module_name,
            &pascal_state,
        ));
    }

    output
}

/// Generates import lines by scanning the IR for types that need imports.
pub(crate) fn generate_imports(packets: &[&PacketDef]) -> String {
    let mut output = String::new();
    let mut needs_derive = false;
    let mut basalt_imports = BTreeSet::new();

    for packet in packets {
        collect_imports_from_fields(&packet.fields, &mut needs_derive, &mut basalt_imports);
    }

    if needs_derive {
        output.push_str("use basalt_derive::{packet, Encode, Decode, EncodedSize};\n");
    } else {
        output.push_str("use basalt_derive::packet;\n");
    }

    if !basalt_imports.is_empty() {
        let imports: Vec<&str> = basalt_imports.into_iter().collect();
        output.push_str(&format!("use basalt_types::{{{}}};\n", imports.join(", ")));
    }

    output
}

/// Recursively collects import requirements from a list of resolved fields.
fn collect_imports_from_fields(
    fields: &[ResolvedField],
    needs_derive: &mut bool,
    basalt_imports: &mut BTreeSet<&'static str>,
) {
    for field in fields {
        collect_imports_from_type(&field.protocol_type, needs_derive, basalt_imports);
    }
}

/// Collects only the basalt-types imports actually referenced by a
/// list of resolved fields, treating `NbtCompound` separately because
/// it lives under `basalt_types::nbt::NbtCompound`.
///
/// Used by the play-codegen pass when generating
/// `crates/basalt-protocol/src/packets/play/types.rs` — that file
/// always pulls in the derive macros, so we only need the runtime
/// import set.
pub(crate) fn collect_basalt_imports_from_fields(
    fields: &[ResolvedField],
    basalt_imports: &mut BTreeSet<&'static str>,
    needs_nbt: &mut bool,
) {
    for field in fields {
        collect_basalt_imports_from_type(&field.protocol_type, basalt_imports, needs_nbt);
    }
}

/// Collects basalt-types imports from a single `ProtocolType`.
fn collect_basalt_imports_from_type(
    pt: &ProtocolType,
    basalt_imports: &mut BTreeSet<&'static str>,
    needs_nbt: &mut bool,
) {
    match pt {
        ProtocolType::NbtCompound | ProtocolType::OptionalNbt => {
            *needs_nbt = true;
        }
        ProtocolType::Uuid => {
            basalt_imports.insert("Uuid");
        }
        ProtocolType::Position => {
            basalt_imports.insert("Position");
        }
        ProtocolType::Slot => {
            basalt_imports.insert("Slot");
        }
        ProtocolType::Vec2f => {
            basalt_imports.insert("Vec2f");
        }
        ProtocolType::Vec3f => {
            basalt_imports.insert("Vec3f");
        }
        ProtocolType::Vec3f64 => {
            basalt_imports.insert("Vec3f64");
        }
        ProtocolType::Vec3i16 => {
            basalt_imports.insert("Vec3i16");
        }
        ProtocolType::Array { inner, .. }
        | ProtocolType::Optional(inner)
        | ProtocolType::Boxed(inner) => {
            collect_basalt_imports_from_type(inner, basalt_imports, needs_nbt);
        }
        ProtocolType::InlineStruct { fields, .. } => {
            collect_basalt_imports_from_fields(fields, basalt_imports, needs_nbt);
        }
        ProtocolType::SwitchEnum { variants, .. } => {
            for variant in variants {
                collect_basalt_imports_from_fields(&variant.fields, basalt_imports, needs_nbt);
            }
        }
        _ => {}
    }
}

/// Recursively collects import requirements from a protocol type.
fn collect_imports_from_type(
    pt: &ProtocolType,
    needs_derive: &mut bool,
    basalt_imports: &mut BTreeSet<&'static str>,
) {
    if let Some(import) = pt.basalt_import() {
        basalt_imports.insert(import);
    }
    if pt.needs_derive_imports() {
        *needs_derive = true;
    }
    match pt {
        ProtocolType::Array { inner, .. } | ProtocolType::Optional(inner) => {
            collect_imports_from_type(inner, needs_derive, basalt_imports);
        }
        ProtocolType::InlineStruct { fields, .. } => {
            collect_imports_from_fields(fields, needs_derive, basalt_imports);
        }
        ProtocolType::SwitchEnum { variants, kind, .. } => {
            // Shared switch enums live in `play/types.rs` and pull
            // their own imports there. Only descend into Inline
            // variants (those emitted alongside this packet).
            if *kind == crate::types::SwitchEnumKind::Inline {
                for variant in variants {
                    collect_imports_from_fields(&variant.fields, needs_derive, basalt_imports);
                }
            }
        }
        ProtocolType::Boxed(inner) => {
            collect_imports_from_type(inner, needs_derive, basalt_imports);
        }
        _ => {}
    }
}

/// Generates a Rust struct for a single packet definition.
///
/// Walks the IR to emit inline structs and switch enums before the
/// packet struct itself, then emits the struct with `#[packet(id)]`.
pub(crate) fn generate_packet_struct(packet: &PacketDef) -> String {
    let mut out = String::new();

    // Emit inline types (structs and enums) before the packet struct
    for field in &packet.fields {
        emit_inline_types(&field.protocol_type, &packet.name, &mut out);
    }

    if packet.fields.is_empty() {
        out.push_str("#[derive(Debug, Clone, Default, PartialEq)]\n");
        out.push_str(&format!("#[packet(id = {})]\n", packet.id));
        out.push_str(&format!("pub struct {};\n", packet.name));
    } else {
        out.push_str("#[derive(Debug, Clone, Default, PartialEq)]\n");
        out.push_str(&format!("#[packet(id = {})]\n", packet.id));
        out.push_str(&format!("pub struct {} {{\n", packet.name));
        for field in &packet.fields {
            let (rust_type, attr) = field.protocol_type.to_rust();
            if let Some(attr) = &attr {
                out.push_str(&format!("    #[field({attr})]\n"));
            }
            out.push_str(&format!("    pub {}: {rust_type},\n", field.name));
        }
        out.push_str("}\n");
    }

    out
}

/// Recursively emits inline type definitions (structs and enums)
/// that need to appear before the packet struct.
fn emit_inline_types(pt: &ProtocolType, packet_name: &str, out: &mut String) {
    match pt {
        ProtocolType::InlineStruct { name, fields } => {
            // Emit nested inline types first
            for field in fields {
                emit_inline_types(&field.protocol_type, packet_name, out);
            }
            out.push_str(&format!(
                "/// Inline data structure used by [`{packet_name}`].\n"
            ));
            out.push_str(
                "#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]\n",
            );
            out.push_str(&format!("pub struct {name} {{\n"));
            for field in fields {
                let (rust_type, attr) = field.protocol_type.to_rust();
                if let Some(attr) = &attr {
                    out.push_str(&format!("    #[field({attr})]\n"));
                }
                out.push_str(&format!("    pub {}: {rust_type},\n", field.name));
            }
            out.push_str("}\n\n");
        }
        ProtocolType::SwitchEnum {
            name,
            variants,
            kind,
        } => {
            // Shared types are emitted once in `play/types.rs`.
            if *kind == crate::types::SwitchEnumKind::Shared {
                return;
            }
            emit_switch_enum(name, variants, packet_name, out);
        }
        ProtocolType::Array { inner, .. } | ProtocolType::Optional(inner) => {
            emit_inline_types(inner, packet_name, out);
        }
        _ => {}
    }
}

/// Emits a switch enum definition with `#[variant(id)]` attributes
/// and a `Default` impl.
fn emit_switch_enum(name: &str, variants: &[SwitchVariant], packet_name: &str, out: &mut String) {
    out.push_str(&format!("/// Switch enum used by [`{packet_name}`].\n"));
    write_switch_enum_body(name, variants, out);
}

/// Emits a shared switch-enum definition without the
/// per-packet documentation comment. Used by the play-codegen pass
/// when collecting `Shared`-kind enums into `play/types.rs`.
pub(crate) fn emit_named_switch_enum(name: &str, variants: &[SwitchVariant], out: &mut String) {
    write_switch_enum_body(name, variants, out);
}

/// Shared body for [`emit_switch_enum`] / [`emit_named_switch_enum`].
///
/// Strategy for `Default`:
/// - If any variant is a unit (no fields), pick the first such
///   variant and use `#[derive(Default)]` with `#[default]` on it.
///   This is idempotent and trivially correct.
/// - Otherwise, hand-write `Default::default()` returning the first
///   variant whose fields contain no `Boxed` self-reference — using
///   such a variant would recurse infinitely through `Default`.
/// - If neither path applies (every variant contains a `Boxed`
///   self-reference), panic at codegen time. The only way to hit
///   this is a pathological JSON definition; our current protocol
///   has no such type.
fn write_switch_enum_body(name: &str, variants: &[SwitchVariant], out: &mut String) {
    let default_unit = variants.iter().position(|v| v.fields.is_empty());
    let derive_default = default_unit.is_some();

    if derive_default {
        out.push_str("#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]\n");
    } else {
        out.push_str("#[derive(Debug, Clone, PartialEq, Encode, Decode, EncodedSize)]\n");
    }
    out.push_str(&format!("pub enum {name} {{\n"));

    for (i, variant) in variants.iter().enumerate() {
        out.push_str(&format!("    #[variant(id = {})]\n", variant.id));
        if Some(i) == default_unit {
            out.push_str("    #[default]\n");
        }
        if variant.fields.is_empty() {
            out.push_str(&format!("    {},\n", variant.name));
        } else {
            out.push_str(&format!("    {} {{\n", variant.name));
            for field in &variant.fields {
                let (rust_type, attr) = field.protocol_type.to_rust();
                if let Some(attr) = &attr {
                    out.push_str(&format!("        #[field({attr})]\n"));
                }
                out.push_str(&format!("        {}: {rust_type},\n", field.name));
            }
            out.push_str("    },\n");
        }
    }

    out.push_str("}\n\n");

    if derive_default {
        return;
    }

    let safe_first = variants.iter().find(|v| {
        v.fields
            .iter()
            .all(|f| !matches!(f.protocol_type, ProtocolType::Boxed(_)))
    });
    let chosen = safe_first.unwrap_or_else(|| {
        panic!(
            "enum `{name}` has no variant safe for Default: every variant contains a Boxed self-reference",
        );
    });

    out.push_str(&format!(
        "impl Default for {name} {{\n    fn default() -> Self {{\n        Self::{}",
        chosen.name
    ));
    if chosen.fields.is_empty() {
        out.push_str("\n    }\n}\n");
    } else {
        out.push_str(" {\n");
        for field in &chosen.fields {
            out.push_str(&format!(
                "            {}: Default::default(),\n",
                field.name
            ));
        }
        out.push_str("        }\n    }\n}\n");
    }
}

/// Generates a direction dispatch enum with `decode_by_id`.
pub(crate) fn generate_direction_enum(
    enum_name: &str,
    packets: &[PacketDef],
    state_name: &str,
    state_pascal: &str,
) -> String {
    let mut out = String::new();

    let direction = if enum_name.starts_with("Serverbound") {
        "serverbound"
    } else {
        "clientbound"
    };
    out.push_str(&format!(
        "/// {direction} packets in the {state_pascal} state.\n"
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));
    for packet in packets {
        let variant = short_variant_name(&packet.name, state_pascal);
        out.push_str(&format!("    {variant}({}),\n", packet.name));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl {enum_name} {{\n"));
    out.push_str("    /// Decodes a packet from its ID and payload.\n");
    out.push_str("    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {\n");
    out.push_str("        match id {\n");
    for packet in packets {
        let variant = short_variant_name(&packet.name, state_pascal);
        out.push_str(&format!(
            "            {}::PACKET_ID => Ok(Self::{variant}({}::decode(buf)?)),\n",
            packet.name, packet.name
        ));
    }
    out.push_str(&format!(
        "            _ => Err(Error::UnknownPacket {{ id, state: \"{state_name}\" }}),\n"
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::ProtocolType;

    #[test]
    fn generate_unit_struct() {
        let packet = PacketDef {
            name: "TestPingStart".into(),
            id: "0x00".into(),
            fields: vec![],
        };
        let code = generate_packet_struct(&packet);
        assert!(code.contains("#[packet(id = 0x00)]"));
        assert!(code.contains("pub struct TestPingStart;"));
    }

    #[test]
    fn generate_struct_with_fields() {
        let packet = PacketDef {
            name: "TestLogin".into(),
            id: "0x01".into(),
            fields: vec![
                ResolvedField {
                    name: "username".into(),
                    protocol_type: ProtocolType::String,
                },
                ResolvedField {
                    name: "protocol_version".into(),
                    protocol_type: ProtocolType::VarInt,
                },
            ],
        };
        let code = generate_packet_struct(&packet);
        assert!(code.contains("#[packet(id = 0x01)]"));
        assert!(code.contains("pub struct TestLogin"));
        assert!(code.contains("pub username: String"));
        assert!(code.contains("#[field(varint)]"));
        assert!(code.contains("pub protocol_version: i32"));
    }

    #[test]
    fn generate_struct_with_inline() {
        let packet = PacketDef {
            name: "TestSuccess".into(),
            id: "0x02".into(),
            fields: vec![ResolvedField {
                name: "items".into(),
                protocol_type: ProtocolType::Array {
                    count: crate::types::CountType::VarInt,
                    inner: Box::new(ProtocolType::InlineStruct {
                        name: "TestSuccessItems".into(),
                        fields: vec![ResolvedField {
                            name: "name".into(),
                            protocol_type: ProtocolType::String,
                        }],
                    }),
                },
            }],
        };
        let code = generate_packet_struct(&packet);
        assert!(code.contains("pub struct TestSuccessItems"));
        assert!(code.contains("pub struct TestSuccess"));
    }

    #[test]
    fn generate_enum_with_dispatch() {
        let packets = vec![
            PacketDef {
                name: "ServerboundTestPing".into(),
                id: "0x00".into(),
                fields: vec![],
            },
            PacketDef {
                name: "ServerboundTestStart".into(),
                id: "0x01".into(),
                fields: vec![],
            },
        ];
        let code = generate_direction_enum("ServerboundTestPacket", &packets, "test", "Test");
        assert!(code.contains("pub enum ServerboundTestPacket"));
        assert!(code.contains("Ping(ServerboundTestPing)"));
        assert!(code.contains("Start(ServerboundTestStart)"));
        assert!(code.contains("decode_by_id"));
        assert!(code.contains("ServerboundTestPing::PACKET_ID"));
        assert!(code.contains("state: \"test\""));
    }

    #[test]
    fn generate_module_from_mock_json() {
        let json: Value = serde_json::from_str(r#"{
            "toServer": {
                "types": {
                    "packet": ["container", [
                        {"name": "name", "type": ["mapper", {"type": "varint", "mappings": {"0x00": "ping_start", "0x01": "ping"}}]},
                        {"name": "params", "type": ["switch", {"compareTo": "name", "fields": {"ping_start": "packet_ping_start", "ping": "packet_ping"}}]}
                    ]],
                    "packet_ping_start": ["container", []],
                    "packet_ping": ["container", [{"name": "time", "type": "i64"}]]
                }
            },
            "toClient": {
                "types": {
                    "packet": ["container", [
                        {"name": "name", "type": ["mapper", {"type": "varint", "mappings": {"0x00": "response"}}]},
                        {"name": "params", "type": ["switch", {"compareTo": "name", "fields": {"response": "packet_response"}}]}
                    ]],
                    "packet_response": ["container", [{"name": "data", "type": "string"}]]
                }
            }
        }"#).unwrap();

        let code = generate_state_module(&json, "test", &Value::Null);
        assert!(code.contains("Test state packet definitions"));
        assert!(code.contains("ServerboundTestPingStart"));
        assert!(code.contains("ServerboundTestPing"));
        assert!(code.contains("ClientboundTestResponse"));
        assert!(code.contains("ServerboundTestPacket"));
        assert!(code.contains("ClientboundTestPacket"));
        assert!(code.contains("decode_by_id"));
    }
}
