//! Rust source code generation from parsed packet definitions.
//!
//! Turns `PacketDef` values into formatted Rust source code: packet
//! structs with `#[packet(id)]` attributes, inline helper structs,
//! direction dispatch enums, and complete state module files.

use std::fs;
use std::path::Path;

use serde_json::Value;

use crate::helpers::{short_variant_name, to_pascal_case};
use crate::parser::parse_direction;
use crate::types::PacketDef;

/// Generates the `packets/mod.rs` file by scanning existing `.rs` files
/// and directories in the packets output directory.
pub(crate) fn generate_packets_mod(workspace_root: &Path, packets_dir: &str) -> String {
    let dir = workspace_root.join(packets_dir);
    let mut modules: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", dir.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().to_string_lossy().to_string();
            let file_type = entry.file_type().ok()?;
            if file_type.is_dir() {
                // Directory with mod.rs inside = a module
                Some(name)
            } else if name.ends_with(".rs") && name != "mod.rs" {
                Some(name.strip_suffix(".rs").unwrap().to_string())
            } else {
                None
            }
        })
        .collect();
    modules.sort();

    let mut out = String::new();
    out.push_str("//! Minecraft packet definitions organized by connection state.\n");
    out.push_str("//!\n");
    out.push_str("//! Each submodule contains the packet structs for one connection state,\n");
    out.push_str("//! along with direction-specific enums (serverbound/clientbound) that\n");
    out.push_str("//! enable exhaustive pattern matching on received packets.\n");
    out.push_str("//!\n");
    out.push_str("//! Auto-generated by `cargo xt codegen`. Do not edit manually.\n\n");
    for module in &modules {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}

/// Generates a complete Rust module for one protocol state.
///
/// Parses both directions (serverbound/clientbound), collects all type
/// imports, generates packet structs with inline helpers, and emits
/// direction dispatch enums with `decode_by_id`.
pub(crate) fn generate_state_module(state: &Value, module_name: &str) -> String {
    let mut output = String::new();

    let pascal_state = to_pascal_case(module_name);

    // Module header
    output.push_str(&format!("//! {pascal_state} state packet definitions.\n"));
    output.push_str("//!\n");
    output.push_str("//! Auto-generated by `cargo xt codegen` from minecraft-data.\n");
    output.push_str("//! Do not edit manually — changes will be overwritten.\n\n");
    let serverbound = parse_direction(state, "toServer", "Serverbound", &pascal_state);
    let clientbound = parse_direction(state, "toClient", "Clientbound", &pascal_state);

    let all_packets: Vec<&PacketDef> = serverbound.iter().chain(clientbound.iter()).collect();

    output.push_str(&generate_imports(&all_packets));
    output.push_str("use basalt_types::Decode as _;\n");
    output.push_str("\nuse crate::error::{Error, Result};\n\n");

    // Generate serverbound packet structs
    if !serverbound.is_empty() {
        output.push_str("// -- Serverbound packets --\n\n");
        for packet in &serverbound {
            output.push_str(&generate_packet_struct(packet));
            output.push('\n');
        }
    }

    // Generate clientbound packet structs
    if !clientbound.is_empty() {
        output.push_str("// -- Clientbound packets --\n\n");
        for packet in &clientbound {
            output.push_str(&generate_packet_struct(packet));
            output.push('\n');
        }
    }

    // Generate direction enums
    if !serverbound.is_empty() {
        output.push_str(&generate_direction_enum(
            &format!("Serverbound{pascal_state}Packet"),
            &serverbound,
            module_name,
            &pascal_state,
        ));
        output.push('\n');
    }

    if !clientbound.is_empty() {
        output.push_str(&generate_direction_enum(
            &format!("Clientbound{pascal_state}Packet"),
            &clientbound,
            module_name,
            &pascal_state,
        ));
    }

    output
}

/// Generates import lines for a set of packets.
///
/// Scans all field types to determine which `basalt_types` imports
/// are needed, and whether inline structs require the derive macros
/// (Encode, Decode, EncodedSize) to be imported alongside `packet`.
pub(crate) fn generate_imports(packets: &[&PacketDef]) -> String {
    let mut output = String::new();

    let has_inline_structs = packets.iter().any(|p| !p.inline_structs.is_empty());

    let all_types: Vec<&str> = packets
        .iter()
        .flat_map(|p| {
            let mut types: Vec<&str> = p.fields.iter().map(|f| f.rust_type.as_str()).collect();
            for s in &p.inline_structs {
                for f in &s.fields {
                    types.push(f.rust_type.as_str());
                }
            }
            types
        })
        .collect();

    let needs = |name: &str| {
        all_types.iter().any(|t| {
            *t == name || t.contains(&format!("<{name}>")) || t.contains(&format!("{name},"))
        })
    };

    if has_inline_structs {
        output.push_str("use basalt_derive::{packet, Encode, Decode, EncodedSize};\n");
    } else {
        output.push_str("use basalt_derive::packet;\n");
    }

    let mut basalt_imports = Vec::new();
    for (type_name, import_name) in [
        ("Uuid", "Uuid"),
        ("Position", "Position"),
        ("NbtCompound", "NbtCompound"),
        ("Slot", "Slot"),
        ("Vec2f", "Vec2f"),
        ("Vec3f64", "Vec3f64"),
        ("Vec3f", "Vec3f"),
        ("Vec3i16", "Vec3i16"),
    ] {
        if needs(type_name) {
            basalt_imports.push(import_name);
        }
    }
    if !basalt_imports.is_empty() {
        output.push_str(&format!(
            "use basalt_types::{{{}}};\n",
            basalt_imports.join(", ")
        ));
    }

    output
}

/// Generates a Rust struct for a single packet definition.
///
/// Emits any inline helper structs first (with derive macros for
/// Encode/Decode/EncodedSize), then the packet struct itself with
/// the `#[packet(id = ...)]` attribute.
pub(crate) fn generate_packet_struct(packet: &PacketDef) -> String {
    let mut out = String::new();

    for inline in &packet.inline_structs {
        out.push_str(&format!(
            "/// Inline data structure used by [`{}`].\n",
            packet.name
        ));
        out.push_str("#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]\n");
        out.push_str(&format!("pub struct {} {{\n", inline.name));
        for field in &inline.fields {
            if let Some(attr) = &field.attribute {
                out.push_str(&format!("    #[field({attr})]\n"));
            }
            out.push_str(&format!("    pub {}: {},\n", field.name, field.rust_type));
        }
        out.push_str("}\n\n");
    }

    if packet.fields.is_empty() {
        out.push_str("#[derive(Debug, Clone, Default, PartialEq)]\n");
        out.push_str(&format!("#[packet(id = {})]\n", packet.id));
        out.push_str(&format!("pub struct {};\n", packet.name));
    } else {
        out.push_str("#[derive(Debug, Clone, Default, PartialEq)]\n");
        out.push_str(&format!("#[packet(id = {})]\n", packet.id));
        out.push_str(&format!("pub struct {} {{\n", packet.name));
        for field in &packet.fields {
            if let Some(attr) = &field.attribute {
                out.push_str(&format!("    #[field({attr})]\n"));
            }
            out.push_str(&format!("    pub {}: {},\n", field.name, field.rust_type));
        }
        out.push_str("}\n");
    }

    out
}

/// Generates a direction dispatch enum with `decode_by_id`.
///
/// The enum has one variant per packet, and `decode_by_id` dispatches
/// on the packet ID to decode the correct type. Unknown IDs return
/// `Error::UnknownPacket`.
pub(crate) fn generate_direction_enum(
    enum_name: &str,
    packets: &[PacketDef],
    state_name: &str,
    state_pascal: &str,
) -> String {
    let mut out = String::new();

    let direction = if enum_name.starts_with("Serverbound") {
        "serverbound"
    } else {
        "clientbound"
    };
    out.push_str(&format!(
        "/// {direction} packets in the {state_pascal} state.\n"
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));
    for packet in packets {
        let variant = short_variant_name(&packet.name, state_pascal);
        out.push_str(&format!("    {variant}({}),\n", packet.name));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl {enum_name} {{\n"));
    out.push_str("    /// Decodes a packet from its ID and payload.\n");
    out.push_str("    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {\n");
    out.push_str("        match id {\n");
    for packet in packets {
        let variant = short_variant_name(&packet.name, state_pascal);
        out.push_str(&format!(
            "            {}::PACKET_ID => Ok(Self::{variant}({}::decode(buf)?)),\n",
            packet.name, packet.name
        ));
    }
    out.push_str(&format!(
        "            _ => Err(Error::UnknownPacket {{ id, state: \"{state_name}\" }}),\n"
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{FieldDef, InlineStruct};

    #[test]
    fn generate_unit_struct() {
        let packet = PacketDef {
            name: "TestPingStart".into(),
            id: "0x00".into(),
            fields: vec![],
            inline_structs: vec![],
        };
        let code = generate_packet_struct(&packet);
        assert!(code.contains("#[packet(id = 0x00)]"));
        assert!(code.contains("pub struct TestPingStart;"));
    }

    #[test]
    fn generate_struct_with_fields() {
        let packet = PacketDef {
            name: "TestLogin".into(),
            id: "0x01".into(),
            fields: vec![
                FieldDef {
                    name: "username".into(),
                    rust_type: "String".into(),
                    attribute: None,
                },
                FieldDef {
                    name: "protocol_version".into(),
                    rust_type: "i32".into(),
                    attribute: Some("varint".into()),
                },
            ],
            inline_structs: vec![],
        };
        let code = generate_packet_struct(&packet);
        assert!(code.contains("#[packet(id = 0x01)]"));
        assert!(code.contains("pub struct TestLogin"));
        assert!(code.contains("pub username: String"));
        assert!(code.contains("#[field(varint)]"));
        assert!(code.contains("pub protocol_version: i32"));
    }

    #[test]
    fn generate_struct_with_inline() {
        let packet = PacketDef {
            name: "TestSuccess".into(),
            id: "0x02".into(),
            fields: vec![FieldDef {
                name: "items".into(),
                rust_type: "Vec<TestSuccessItems>".into(),
                attribute: Some("length = \"varint\"".into()),
            }],
            inline_structs: vec![InlineStruct {
                name: "TestSuccessItems".into(),
                fields: vec![FieldDef {
                    name: "name".into(),
                    rust_type: "String".into(),
                    attribute: None,
                }],
            }],
        };
        let code = generate_packet_struct(&packet);
        assert!(code.contains("pub struct TestSuccessItems"));
        assert!(code.contains("pub struct TestSuccess"));
    }

    #[test]
    fn generate_enum_with_dispatch() {
        let packets = vec![
            PacketDef {
                name: "ServerboundTestPing".into(),
                id: "0x00".into(),
                fields: vec![],
                inline_structs: vec![],
            },
            PacketDef {
                name: "ServerboundTestStart".into(),
                id: "0x01".into(),
                fields: vec![],
                inline_structs: vec![],
            },
        ];
        let code = generate_direction_enum("ServerboundTestPacket", &packets, "test", "Test");
        assert!(code.contains("pub enum ServerboundTestPacket"));
        assert!(code.contains("Ping(ServerboundTestPing)"));
        assert!(code.contains("Start(ServerboundTestStart)"));
        assert!(code.contains("decode_by_id"));
        assert!(code.contains("ServerboundTestPing::PACKET_ID"));
        assert!(code.contains("state: \"test\""));
    }

    #[test]
    fn generate_module_from_mock_json() {
        let json: Value = serde_json::from_str(r#"{
            "toServer": {
                "types": {
                    "packet": ["container", [
                        {"name": "name", "type": ["mapper", {"type": "varint", "mappings": {"0x00": "ping_start", "0x01": "ping"}}]},
                        {"name": "params", "type": ["switch", {"compareTo": "name", "fields": {"ping_start": "packet_ping_start", "ping": "packet_ping"}}]}
                    ]],
                    "packet_ping_start": ["container", []],
                    "packet_ping": ["container", [{"name": "time", "type": "i64"}]]
                }
            },
            "toClient": {
                "types": {
                    "packet": ["container", [
                        {"name": "name", "type": ["mapper", {"type": "varint", "mappings": {"0x00": "response"}}]},
                        {"name": "params", "type": ["switch", {"compareTo": "name", "fields": {"response": "packet_response"}}]}
                    ]],
                    "packet_response": ["container", [{"name": "data", "type": "string"}]]
                }
            }
        }"#).unwrap();

        let code = generate_state_module(&json, "test");
        assert!(code.contains("Test state packet definitions"));
        assert!(code.contains("ServerboundTestPingStart"));
        assert!(code.contains("ServerboundTestPing"));
        assert!(code.contains("ClientboundTestResponse"));
        assert!(code.contains("ServerboundTestPacket"));
        assert!(code.contains("ClientboundTestPacket"));
        assert!(code.contains("decode_by_id"));
    }
}
