//! Code generation tool for Minecraft protocol packets.
//!
//! Reads packet definitions from the minecraft-data JSON files and generates
//! Rust source code with `#[packet(id)]` attribute macros and typed fields.
//!
//! Usage: `cargo xt codegen`

use serde_json::Value;
use std::collections::BTreeMap;
use std::fs;

/// The Minecraft version to generate packets for.
const VERSION: &str = "1.21.4";

/// Path to the minecraft-data submodule relative to the workspace root.
const MINECRAFT_DATA_PATH: &str = "minecraft-data/data/pc";

/// Output directory for generated packets relative to the workspace root.
const PACKETS_DIR: &str = "crates/basalt-protocol/src/packets";

/// Protocol states to generate, mapped to their JSON key and Rust module name.
const STATES: &[(&str, &str)] = &[
    ("handshaking", "handshake"),
    ("status", "status"),
    ("login", "login"),
];

fn main() {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(|s| s.as_str()) {
        Some("codegen") => codegen(),
        _ => {
            eprintln!("Usage: cargo xt codegen");
            std::process::exit(1);
        }
    }
}

/// Runs the code generation pipeline for all configured states.
fn codegen() {
    let workspace_root = find_workspace_root();
    let protocol_path = workspace_root
        .join(MINECRAFT_DATA_PATH)
        .join(VERSION)
        .join("protocol.json");

    println!("Reading protocol data from {}", protocol_path.display());
    let protocol_json = fs::read_to_string(&protocol_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", protocol_path.display()));

    let protocol: Value = serde_json::from_str(&protocol_json).expect("Failed to parse JSON");

    for &(json_key, module_name) in STATES {
        let state_data = &protocol[json_key];
        if state_data.is_null() {
            eprintln!("Warning: state '{json_key}' not found in protocol.json, skipping");
            continue;
        }

        let code = generate_state_module(state_data, module_name);
        let output_path = workspace_root
            .join(PACKETS_DIR)
            .join(format!("{module_name}.rs"));
        println!("Writing {module_name} packets to {}", output_path.display());
        fs::write(&output_path, &code)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", output_path.display()));
    }

    // Generate packets/mod.rs from files on disk
    let mod_path = workspace_root.join(PACKETS_DIR).join("mod.rs");
    println!("Writing packets mod.rs to {}", mod_path.display());
    let mod_code = generate_packets_mod(&workspace_root);
    fs::write(&mod_path, mod_code)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", mod_path.display()));

    println!("Done. Run `cargo fmt` to format the generated code.");
}

/// Finds the workspace root by looking for Cargo.toml with [workspace].
fn find_workspace_root() -> std::path::PathBuf {
    let mut dir = std::env::current_dir().expect("Failed to get current directory");
    loop {
        let cargo_toml = dir.join("Cargo.toml");
        if cargo_toml.exists() {
            let content = fs::read_to_string(&cargo_toml).unwrap_or_default();
            if content.contains("[workspace]") {
                return dir;
            }
        }
        if !dir.pop() {
            panic!("Could not find workspace root (no Cargo.toml with [workspace])");
        }
    }
}

/// Generates the packets/mod.rs file by scanning existing .rs files.
fn generate_packets_mod(workspace_root: &std::path::Path) -> String {
    let packets_dir = workspace_root.join(PACKETS_DIR);
    let mut modules: Vec<String> = fs::read_dir(&packets_dir)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", packets_dir.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".rs") && name != "mod.rs" {
                Some(name.strip_suffix(".rs").unwrap().to_string())
            } else {
                None
            }
        })
        .collect();
    modules.sort();

    let mut out = String::new();
    out.push_str("//! Minecraft packet definitions organized by connection state.\n");
    out.push_str("//!\n");
    out.push_str("//! Each submodule contains the packet structs for one connection state,\n");
    out.push_str("//! along with direction-specific enums (serverbound/clientbound) that\n");
    out.push_str("//! enable exhaustive pattern matching on received packets.\n");
    out.push_str("//!\n");
    out.push_str("//! Auto-generated by `cargo xt codegen`. Do not edit manually.\n\n");
    for module in &modules {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}

/// Generates a complete Rust module for one protocol state.
fn generate_state_module(state: &Value, module_name: &str) -> String {
    let mut output = String::new();

    let pascal_state = to_pascal_case(module_name);

    // Module header
    output.push_str(&format!("//! {pascal_state} state packet definitions.\n"));
    output.push_str("//!\n");
    output.push_str("//! Auto-generated by `cargo xt codegen` from minecraft-data.\n");
    output.push_str("//! Do not edit manually — changes will be overwritten.\n\n");
    let serverbound = parse_direction(state, "toServer", "Serverbound", &pascal_state);
    let clientbound = parse_direction(state, "toClient", "Clientbound", &pascal_state);

    let has_inline_structs = serverbound
        .iter()
        .chain(clientbound.iter())
        .any(|p| !p.inline_structs.is_empty());

    let needs_uuid = serverbound.iter().chain(clientbound.iter()).any(|p| {
        p.fields.iter().any(|f| f.rust_type.contains("Uuid"))
            || p.inline_structs
                .iter()
                .any(|s| s.fields.iter().any(|f| f.rust_type.contains("Uuid")))
    });

    if has_inline_structs {
        output.push_str("use basalt_derive::{packet, Encode, Decode, EncodedSize};\n");
    } else {
        output.push_str("use basalt_derive::packet;\n");
    }
    output.push_str("use basalt_types::Decode as _;\n");
    if needs_uuid {
        output.push_str("use basalt_types::Uuid;\n");
    }

    output.push_str("\nuse crate::error::{Error, Result};\n\n");

    // Generate serverbound packet structs
    if !serverbound.is_empty() {
        output.push_str("// -- Serverbound packets --\n\n");
        for packet in &serverbound {
            output.push_str(&generate_packet_struct(packet));
            output.push('\n');
        }
    }

    // Generate clientbound packet structs
    if !clientbound.is_empty() {
        output.push_str("// -- Clientbound packets --\n\n");
        for packet in &clientbound {
            output.push_str(&generate_packet_struct(packet));
            output.push('\n');
        }
    }

    // Generate direction enums
    if !serverbound.is_empty() {
        output.push_str(&generate_direction_enum(
            &format!("Serverbound{pascal_state}Packet"),
            &serverbound,
            module_name,
            &pascal_state,
        ));
        output.push('\n');
    }

    if !clientbound.is_empty() {
        output.push_str(&generate_direction_enum(
            &format!("Clientbound{pascal_state}Packet"),
            &clientbound,
            module_name,
            &pascal_state,
        ));
    }

    // Generate tests
    output.push('\n');
    output.push_str(&generate_tests(
        &serverbound,
        &clientbound,
        &pascal_state,
        module_name,
    ));

    output
}

// -- Data structures --

#[derive(Debug)]
struct PacketDef {
    name: String,
    id: String,
    fields: Vec<FieldDef>,
    inline_structs: Vec<InlineStruct>,
}

#[derive(Debug)]
struct FieldDef {
    name: String,
    rust_type: String,
    attribute: Option<String>,
}

#[derive(Debug)]
struct InlineStruct {
    name: String,
    fields: Vec<FieldDef>,
}

// -- Parsing --

fn parse_direction(
    state: &Value,
    direction: &str,
    dir_prefix: &str,
    state_pascal: &str,
) -> Vec<PacketDef> {
    let dir_data = &state[direction];
    if dir_data.is_null() {
        return Vec::new();
    }

    let types = &dir_data["types"];
    let packet_mapper = &types["packet"];
    if packet_mapper.is_null() {
        return Vec::new();
    }

    let mappings = &packet_mapper[1][0]["type"][1]["mappings"];
    let id_map: BTreeMap<String, String> = mappings
        .as_object()
        .expect("mappings should be an object")
        .iter()
        .map(|(id, name)| (name.as_str().unwrap().to_string(), id.clone()))
        .collect();

    let mut packets = Vec::new();
    for (name, id) in &id_map {
        let type_key = format!("packet_{name}");

        // Check if the switch redirects to a common packet
        let switch_fields = &packet_mapper[1][1]["type"][1]["fields"];
        let actual_type_key = switch_fields[name.as_str()].as_str().unwrap_or(&type_key);

        if actual_type_key.starts_with("packet_common_") {
            continue;
        }

        let packet_type = &types[actual_type_key];
        if packet_type.is_null() {
            eprintln!("Warning: packet type {actual_type_key} not found, skipping");
            continue;
        }

        let struct_name = format!("{dir_prefix}{state_pascal}{}", to_pascal_case(name));
        let (fields, inline_structs) = parse_container_fields(packet_type, &struct_name);

        packets.push(PacketDef {
            name: struct_name,
            id: id.clone(),
            fields,
            inline_structs,
        });
    }

    packets
}

fn parse_container_fields(
    container: &Value,
    parent_name: &str,
) -> (Vec<FieldDef>, Vec<InlineStruct>) {
    let mut fields = Vec::new();
    let mut inline_structs = Vec::new();

    let field_array = container[1]
        .as_array()
        .expect("container fields should be an array");

    for (i, field) in field_array.iter().enumerate() {
        let field_name = field["name"]
            .as_str()
            .expect("field should have a name")
            .to_string();
        let rust_name = to_snake_case(&field_name);
        let field_type = &field["type"];
        let is_last = i == field_array.len() - 1;

        let (rust_type, attribute, inline) =
            map_type(field_type, parent_name, &field_name, is_last);

        if let Some(inline_struct) = inline {
            inline_structs.push(inline_struct);
        }

        fields.push(FieldDef {
            name: rust_name,
            rust_type,
            attribute,
        });
    }

    (fields, inline_structs)
}

fn map_type(
    type_def: &Value,
    parent_name: &str,
    field_name: &str,
    is_last: bool,
) -> (String, Option<String>, Option<InlineStruct>) {
    match type_def {
        Value::String(s) => match s.as_str() {
            "varint" => ("i32".into(), Some("varint".into()), None),
            "varlong" => ("i64".into(), Some("varlong".into()), None),
            "string" => ("String".into(), None, None),
            "bool" => ("bool".into(), None, None),
            "u8" => ("u8".into(), None, None),
            "u16" => ("u16".into(), None, None),
            "u32" => ("u32".into(), None, None),
            "u64" => ("u64".into(), None, None),
            "i8" => ("i8".into(), None, None),
            "i16" => ("i16".into(), None, None),
            "i32" => ("i32".into(), None, None),
            "i64" => ("i64".into(), None, None),
            "f32" => ("f32".into(), None, None),
            "f64" => ("f64".into(), None, None),
            "UUID" => ("Uuid".into(), None, None),
            "restBuffer" => {
                if is_last {
                    ("Vec<u8>".into(), Some("rest".into()), None)
                } else {
                    ("Vec<u8>".into(), None, None)
                }
            }
            other => {
                eprintln!("Warning: unknown type '{other}', using Vec<u8>");
                ("Vec<u8>".into(), None, None)
            }
        },
        Value::Array(arr) if arr.len() == 2 => {
            let type_name = arr[0].as_str().unwrap_or("");
            match type_name {
                "buffer" => {
                    let count_type = arr[1]["countType"].as_str().unwrap_or("varint");
                    if count_type == "varint" {
                        ("Vec<u8>".into(), Some("length = \"varint\"".into()), None)
                    } else {
                        ("Vec<u8>".into(), None, None)
                    }
                }
                "option" => {
                    let inner_type = &arr[1];
                    let (inner_rust, _inner_attr, inline) =
                        map_type(inner_type, parent_name, field_name, is_last);
                    (
                        format!("Option<{inner_rust}>"),
                        Some("optional".into()),
                        inline,
                    )
                }
                "array" => {
                    let count_type = arr[1]["countType"].as_str().unwrap_or("varint");
                    let inner_type = &arr[1]["type"];

                    if inner_type.is_array() && inner_type[0].as_str() == Some("container") {
                        let struct_name = format!("{}{}", parent_name, to_pascal_case(field_name));
                        let (inner_fields, _nested_inlines) =
                            parse_container_fields(inner_type, &struct_name);
                        let inline = InlineStruct {
                            name: struct_name.clone(),
                            fields: inner_fields,
                        };

                        if count_type == "varint" {
                            (
                                format!("Vec<{struct_name}>"),
                                Some("length = \"varint\"".into()),
                                Some(inline),
                            )
                        } else {
                            (format!("Vec<{struct_name}>"), None, Some(inline))
                        }
                    } else {
                        let (inner_rust, _, inline) =
                            map_type(inner_type, parent_name, field_name, false);
                        if count_type == "varint" {
                            (
                                format!("Vec<{inner_rust}>"),
                                Some("length = \"varint\"".into()),
                                inline,
                            )
                        } else {
                            (format!("Vec<{inner_rust}>"), None, inline)
                        }
                    }
                }
                _ => {
                    eprintln!("Warning: unknown compound type '{type_name}', using Vec<u8>");
                    ("Vec<u8>".into(), None, None)
                }
            }
        }
        _ => {
            eprintln!("Warning: unexpected type format, using Vec<u8>");
            ("Vec<u8>".into(), None, None)
        }
    }
}

// -- Code generation --

fn generate_packet_struct(packet: &PacketDef) -> String {
    let mut out = String::new();

    for inline in &packet.inline_structs {
        out.push_str(&format!(
            "/// Inline data structure used by [`{}`].\n",
            packet.name
        ));
        out.push_str("#[derive(Debug, Clone, PartialEq, Encode, Decode, EncodedSize)]\n");
        out.push_str(&format!("pub struct {} {{\n", inline.name));
        for field in &inline.fields {
            if let Some(attr) = &field.attribute {
                out.push_str(&format!("    #[field({attr})]\n"));
            }
            out.push_str(&format!("    pub {}: {},\n", field.name, field.rust_type));
        }
        out.push_str("}\n\n");
    }

    if packet.fields.is_empty() {
        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str(&format!("#[packet(id = {})]\n", packet.id));
        out.push_str(&format!("pub struct {};\n", packet.name));
    } else {
        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str(&format!("#[packet(id = {})]\n", packet.id));
        out.push_str(&format!("pub struct {} {{\n", packet.name));
        for field in &packet.fields {
            if let Some(attr) = &field.attribute {
                out.push_str(&format!("    #[field({attr})]\n"));
            }
            out.push_str(&format!("    pub {}: {},\n", field.name, field.rust_type));
        }
        out.push_str("}\n");
    }

    out
}

fn generate_direction_enum(
    enum_name: &str,
    packets: &[PacketDef],
    state_name: &str,
    state_pascal: &str,
) -> String {
    let mut out = String::new();

    let direction = if enum_name.starts_with("Serverbound") {
        "serverbound"
    } else {
        "clientbound"
    };
    out.push_str(&format!(
        "/// {direction} packets in the {state_pascal} state.\n"
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));
    for packet in packets {
        let variant = short_variant_name(&packet.name, state_pascal);
        out.push_str(&format!("    {variant}({}),\n", packet.name));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl {enum_name} {{\n"));
    out.push_str("    /// Decodes a packet from its ID and payload.\n");
    out.push_str("    pub fn decode_by_id(id: i32, buf: &mut &[u8]) -> Result<Self> {\n");
    out.push_str("        match id {\n");
    for packet in packets {
        let variant = short_variant_name(&packet.name, state_pascal);
        out.push_str(&format!(
            "            {}::PACKET_ID => Ok(Self::{variant}({}::decode(buf)?)),\n",
            packet.name, packet.name
        ));
    }
    out.push_str(&format!(
        "            _ => Err(Error::UnknownPacket {{ id, state: \"{state_name}\" }}),\n"
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn generate_tests(
    serverbound: &[PacketDef],
    clientbound: &[PacketDef],
    state_pascal: &str,
    _state_name: &str,
) -> String {
    let mut out = String::new();
    out.push_str("#[cfg(test)]\n");
    out.push_str("mod tests {\n");
    out.push_str("    use super::*;\n\n");

    if !serverbound.is_empty() {
        out.push_str("    #[test]\n");
        out.push_str("    fn serverbound_packet_ids() {\n");
        for packet in serverbound {
            out.push_str(&format!(
                "        assert_eq!({}::PACKET_ID, {});\n",
                packet.name, packet.id
            ));
        }
        out.push_str("    }\n\n");

        out.push_str("    #[test]\n");
        out.push_str("    fn unknown_serverbound_id() {\n");
        out.push_str("        let mut cursor: &[u8] = &[];\n");
        out.push_str(&format!(
            "        assert!(Serverbound{state_pascal}Packet::decode_by_id(0xFF, &mut cursor).is_err());\n"
        ));
        out.push_str("    }\n\n");
    }

    if !clientbound.is_empty() {
        out.push_str("    #[test]\n");
        out.push_str("    fn clientbound_packet_ids() {\n");
        for packet in clientbound {
            out.push_str(&format!(
                "        assert_eq!({}::PACKET_ID, {});\n",
                packet.name, packet.id
            ));
        }
        out.push_str("    }\n\n");

        out.push_str("    #[test]\n");
        out.push_str("    fn unknown_clientbound_id() {\n");
        out.push_str("        let mut cursor: &[u8] = &[];\n");
        out.push_str(&format!(
            "        assert!(Clientbound{state_pascal}Packet::decode_by_id(0xFF, &mut cursor).is_err());\n"
        ));
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

// -- Helpers --

/// Removes the direction prefix and state name to get a short enum variant.
/// e.g., "ServerboundLoginEncryptionBegin" → "EncryptionBegin"
fn short_variant_name(full_name: &str, state_pascal: &str) -> String {
    let without_dir = full_name
        .strip_prefix("Serverbound")
        .or_else(|| full_name.strip_prefix("Clientbound"))
        .unwrap_or(full_name);
    without_dir
        .strip_prefix(state_pascal)
        .unwrap_or(without_dir)
        .to_string()
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = s.chars().collect();
    for i in 0..chars.len() {
        let c = chars[i];
        if c.is_uppercase() {
            let prev_is_lower = i > 0 && chars[i - 1].is_lowercase();
            let next_is_lower = i + 1 < chars.len() && chars[i + 1].is_lowercase();
            if prev_is_lower || (i > 0 && chars[i - 1].is_uppercase() && next_is_lower) {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    match result.as_str() {
        "type" => "r#type".to_string(),
        "match" => "r#match".to_string(),
        _ => result,
    }
}
