//! Play state — chat packets.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::{Decode, Encode, EncodedSize, packet};
use basalt_types::{NbtCompound, Uuid};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x05)]
pub struct ServerboundPlayChatCommand {
    pub command: String,
}

/// Inline data structure used by [`ServerboundPlayChatCommandSigned`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ServerboundPlayChatCommandSignedArgumentsignatures {
    pub argument_name: String,
    #[field(length = "varint")]
    pub signature: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x06)]
pub struct ServerboundPlayChatCommandSigned {
    pub command: String,
    pub timestamp: i64,
    pub salt: i64,
    #[field(length = "varint")]
    pub argument_signatures: Vec<ServerboundPlayChatCommandSignedArgumentsignatures>,
    #[field(varint)]
    pub message_count: i32,
    #[field(length = "varint")]
    pub acknowledged: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x07)]
pub struct ServerboundPlayChatMessage {
    pub message: String,
    pub timestamp: i64,
    pub salt: i64,
    #[field(optional)]
    pub signature: Option<Vec<u8>>,
    #[field(varint)]
    pub offset: i32,
    #[field(length = "varint")]
    pub acknowledged: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x08)]
pub struct ServerboundPlayChatSessionUpdate {
    pub session_uuid: Uuid,
    pub expire_time: i64,
    #[field(length = "varint")]
    pub public_key: Vec<u8>,
    #[field(length = "varint")]
    pub signature: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x04)]
pub struct ServerboundPlayMessageAcknowledgement {
    #[field(varint)]
    pub count: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0d)]
pub struct ServerboundPlayTabComplete {
    #[field(varint)]
    pub transaction_id: i32,
    pub text: String,
}

// -- Clientbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x51)]
pub struct ClientboundPlayActionBar {
    pub text: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0a)]
pub struct ClientboundPlayBossBar {
    pub entity_uuid: Uuid,
    #[field(varint)]
    pub action: i32,
    pub title: Vec<u8>,
    pub health: Vec<u8>,
    pub color: Vec<u8>,
    pub dividers: Vec<u8>,
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x18)]
pub struct ClientboundPlayChatSuggestions {
    #[field(varint)]
    pub action: i32,
    #[field(length = "varint")]
    pub entries: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0f)]
pub struct ClientboundPlayClearTitles {
    pub reset: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x11)]
pub struct ClientboundPlayDeclareCommands {
    #[field(length = "varint")]
    pub nodes: Vec<Vec<u8>>,
    #[field(varint)]
    pub root_index: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1c)]
pub struct ClientboundPlayHideMessage {
    #[field(varint)]
    pub id: i32,
    pub signature: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x74)]
pub struct ClientboundPlayPlayerlistHeader {
    pub header: NbtCompound,
    pub footer: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1e)]
pub struct ClientboundPlayProfilelessChat {
    pub message: NbtCompound,
    pub r#type: Vec<u8>,
    pub name: NbtCompound,
    #[field(optional)]
    pub target: Option<NbtCompound>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x49)]
pub struct ClientboundPlayResetScore {
    pub entity_name: String,
    #[field(optional)]
    pub objective_name: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x5c)]
pub struct ClientboundPlayScoreboardDisplayObjective {
    #[field(varint)]
    pub position: i32,
    pub name: String,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x64)]
pub struct ClientboundPlayScoreboardObjective {
    pub name: String,
    pub action: i8,
    pub display_text: Vec<u8>,
    pub r#type: Vec<u8>,
    pub number_format: Vec<u8>,
    pub styling: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x68)]
pub struct ClientboundPlayScoreboardScore {
    pub item_name: String,
    pub score_name: String,
    #[field(varint)]
    pub value: i32,
    #[field(optional)]
    pub display_name: Option<NbtCompound>,
    #[field(optional)]
    pub number_format: Option<i32>,
    pub styling: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x6a)]
pub struct ClientboundPlaySetTitleSubtitle {
    pub text: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x6c)]
pub struct ClientboundPlaySetTitleText {
    pub text: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x6d)]
pub struct ClientboundPlaySetTitleTime {
    pub fade_in: i32,
    pub stay: i32,
    pub fade_out: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x73)]
pub struct ClientboundPlaySystemChat {
    pub content: NbtCompound,
    pub is_action_bar: bool,
}

/// Inline data structure used by [`ClientboundPlayTabComplete`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayTabCompleteMatches {
    pub r#match: String,
    #[field(optional)]
    pub tooltip: Option<NbtCompound>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x10)]
pub struct ClientboundPlayTabComplete {
    #[field(varint)]
    pub transaction_id: i32,
    #[field(varint)]
    pub start: i32,
    #[field(varint)]
    pub length: i32,
    #[field(length = "varint")]
    pub matches: Vec<ClientboundPlayTabCompleteMatches>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x67)]
pub struct ClientboundPlayTeams {
    pub team: String,
    pub mode: i8,
    pub name: Vec<u8>,
    pub friendly_fire: Vec<u8>,
    pub name_tag_visibility: Vec<u8>,
    pub collision_rule: Vec<u8>,
    pub formatting: Vec<u8>,
    pub prefix: Vec<u8>,
    pub suffix: Vec<u8>,
    pub players: Vec<u8>,
}
