//! Play state — inventory packets.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::{Decode, Encode, EncodedSize, packet};
use basalt_types::{NbtCompound, Position, Slot};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x11)]
pub struct ServerboundPlayCloseWindow {
    #[field(varint)]
    pub window_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x25)]
pub struct ServerboundPlayCraftRecipeRequest {
    #[field(varint)]
    pub window_id: i32,
    #[field(varint)]
    pub recipe_id: i32,
    pub make_all: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0f)]
pub struct ServerboundPlayEnchantItem {
    #[field(varint)]
    pub window_id: i32,
    pub enchantment: i8,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x33)]
pub struct ServerboundPlayHeldItemSlot {
    pub slot_id: i16,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2e)]
pub struct ServerboundPlayNameItem {
    pub name: String,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x22)]
pub struct ServerboundPlayPickItemFromBlock {
    pub position: Position,
    pub include_data: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x23)]
pub struct ServerboundPlayPickItemFromEntity {
    #[field(varint)]
    pub entity_id: i32,
    pub include_data: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x02)]
pub struct ServerboundPlaySelectBundleItem {
    #[field(varint)]
    pub slot_id: i32,
    #[field(varint)]
    pub selected_item_index: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x31)]
pub struct ServerboundPlaySelectTrade {
    #[field(varint)]
    pub slot: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x32)]
pub struct ServerboundPlaySetBeaconEffect {
    #[field(optional)]
    pub primary_effect: Option<i32>,
    #[field(optional)]
    pub secondary_effect: Option<i32>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x36)]
pub struct ServerboundPlaySetCreativeSlot {
    pub slot: i16,
    pub item: Slot,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x12)]
pub struct ServerboundPlaySetSlotState {
    #[field(varint)]
    pub slot_id: i32,
    #[field(varint)]
    pub window_id: i32,
    pub state: bool,
}

/// Inline data structure used by [`ServerboundPlayWindowClick`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ServerboundPlayWindowClickChangedslots {
    pub location: i16,
    pub item: Slot,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x10)]
pub struct ServerboundPlayWindowClick {
    #[field(varint)]
    pub window_id: i32,
    #[field(varint)]
    pub state_id: i32,
    pub slot: i16,
    pub mouse_button: i8,
    #[field(varint)]
    pub mode: i32,
    #[field(length = "varint")]
    pub changed_slots: Vec<ServerboundPlayWindowClickChangedslots>,
    pub cursor_item: Slot,
}

// -- Clientbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x12)]
pub struct ClientboundPlayCloseWindow {
    #[field(varint)]
    pub window_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x14)]
pub struct ClientboundPlayCraftProgressBar {
    #[field(varint)]
    pub window_id: i32,
    pub property: i16,
    pub value: i16,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x39)]
pub struct ClientboundPlayCraftRecipeResponse {
    #[field(varint)]
    pub window_id: i32,
    pub recipe_display: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x63)]
pub struct ClientboundPlayHeldItemSlot {
    #[field(varint)]
    pub slot: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x34)]
pub struct ClientboundPlayOpenBook {
    #[field(varint)]
    pub hand: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x24)]
pub struct ClientboundPlayOpenHorseWindow {
    #[field(varint)]
    pub window_id: i32,
    #[field(varint)]
    pub nb_slots: i32,
    pub entity_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x36)]
pub struct ClientboundPlayOpenSignEntity {
    pub location: Position,
    pub is_front_text: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x35)]
pub struct ClientboundPlayOpenWindow {
    #[field(varint)]
    pub window_id: i32,
    #[field(varint)]
    pub inventory_type: i32,
    pub window_title: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x17)]
pub struct ClientboundPlaySetCooldown {
    pub cooldown_group: String,
    #[field(varint)]
    pub cooldown_ticks: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x5a)]
pub struct ClientboundPlaySetCursorItem {
    pub contents: Slot,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x66)]
pub struct ClientboundPlaySetPlayerInventory {
    #[field(varint)]
    pub slot_id: i32,
    pub contents: Slot,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x15)]
pub struct ClientboundPlaySetSlot {
    #[field(varint)]
    pub window_id: i32,
    #[field(varint)]
    pub state_id: i32,
    pub slot: i16,
    pub item: Slot,
}

/// Inline data structure used by [`ClientboundPlayTradeList`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayTradeListTrades {
    pub input_item1: Vec<u8>,
    pub output_item: Slot,
    #[field(optional)]
    pub input_item2: Option<Vec<u8>>,
    pub trade_disabled: bool,
    pub nb_trade_uses: i32,
    pub maximum_nb_trade_uses: i32,
    pub xp: i32,
    pub special_price: i32,
    pub price_multiplier: f32,
    pub demand: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2e)]
pub struct ClientboundPlayTradeList {
    #[field(varint)]
    pub window_id: i32,
    #[field(length = "varint")]
    pub trades: Vec<ClientboundPlayTradeListTrades>,
    #[field(varint)]
    pub villager_level: i32,
    #[field(varint)]
    pub experience: i32,
    pub is_regular_villager: bool,
    pub can_restock: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x13)]
pub struct ClientboundPlayWindowItems {
    #[field(varint)]
    pub window_id: i32,
    #[field(varint)]
    pub state_id: i32,
    #[field(length = "varint")]
    pub items: Vec<Slot>,
    pub carried_item: Slot,
}

#[cfg(test)]
mod tests {
    use super::*;
    use basalt_types::{Encode as _, EncodedSize as _};

    #[test]
    fn serverbound_play_close_window_roundtrip() {
        let original = ServerboundPlayCloseWindow::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayCloseWindow::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_craft_recipe_request_roundtrip() {
        let original = ServerboundPlayCraftRecipeRequest::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayCraftRecipeRequest::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_enchant_item_roundtrip() {
        let original = ServerboundPlayEnchantItem::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayEnchantItem::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_held_item_slot_roundtrip() {
        let original = ServerboundPlayHeldItemSlot::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayHeldItemSlot::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_name_item_roundtrip() {
        let original = ServerboundPlayNameItem::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayNameItem::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_pick_item_from_block_roundtrip() {
        let original = ServerboundPlayPickItemFromBlock::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPickItemFromBlock::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_pick_item_from_entity_roundtrip() {
        let original = ServerboundPlayPickItemFromEntity::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPickItemFromEntity::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_select_bundle_item_roundtrip() {
        let original = ServerboundPlaySelectBundleItem::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySelectBundleItem::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_select_trade_roundtrip() {
        let original = ServerboundPlaySelectTrade::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySelectTrade::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_set_beacon_effect_roundtrip() {
        let original = ServerboundPlaySetBeaconEffect::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySetBeaconEffect::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_set_creative_slot_roundtrip() {
        let original = ServerboundPlaySetCreativeSlot::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySetCreativeSlot::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_set_slot_state_roundtrip() {
        let original = ServerboundPlaySetSlotState::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySetSlotState::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_window_click_roundtrip() {
        let original = ServerboundPlayWindowClick::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayWindowClick::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_close_window_roundtrip() {
        let original = ClientboundPlayCloseWindow::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayCloseWindow::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_craft_progress_bar_roundtrip() {
        let original = ClientboundPlayCraftProgressBar::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayCraftProgressBar::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_craft_recipe_response_roundtrip() {
        let original = ClientboundPlayCraftRecipeResponse::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayCraftRecipeResponse::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_held_item_slot_roundtrip() {
        let original = ClientboundPlayHeldItemSlot::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayHeldItemSlot::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_open_book_roundtrip() {
        let original = ClientboundPlayOpenBook::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayOpenBook::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_open_horse_window_roundtrip() {
        let original = ClientboundPlayOpenHorseWindow::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayOpenHorseWindow::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_open_sign_entity_roundtrip() {
        let original = ClientboundPlayOpenSignEntity::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayOpenSignEntity::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_open_window_roundtrip() {
        let original = ClientboundPlayOpenWindow::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayOpenWindow::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_set_cooldown_roundtrip() {
        let original = ClientboundPlaySetCooldown::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySetCooldown::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_set_cursor_item_roundtrip() {
        let original = ClientboundPlaySetCursorItem::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySetCursorItem::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_set_player_inventory_roundtrip() {
        let original = ClientboundPlaySetPlayerInventory::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySetPlayerInventory::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_set_slot_roundtrip() {
        let original = ClientboundPlaySetSlot::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySetSlot::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_trade_list_roundtrip() {
        let original = ClientboundPlayTradeList::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayTradeList::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_window_items_roundtrip() {
        let original = ClientboundPlayWindowItems::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayWindowItems::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }
}
