//! Play state — misc packets.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::{Decode, Encode, EncodedSize, packet};
use basalt_types::{NbtCompound, Position, Uuid, Vec2f};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x30)]
pub struct ServerboundPlayAdvancementTab {
    #[field(varint)]
    pub action: i32,
    pub tab_id: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0e)]
pub struct ServerboundPlayConfigurationAcknowledged;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x14)]
pub struct ServerboundPlayCustomPayload {
    pub channel: String,
    #[field(rest)]
    pub data: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x15)]
pub struct ServerboundPlayDebugSampleSubscription {
    #[field(varint)]
    pub r#type: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2d)]
pub struct ServerboundPlayDisplayedRecipe {
    #[field(varint)]
    pub recipe_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x16)]
pub struct ServerboundPlayEditBook {
    #[field(varint)]
    pub hand: i32,
    #[field(length = "varint")]
    pub pages: Vec<String>,
    #[field(optional)]
    pub title: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1a)]
pub struct ServerboundPlayKeepAlive {
    pub keep_alive_id: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x24)]
pub struct ServerboundPlayPingRequest {
    pub id: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2b)]
pub struct ServerboundPlayPong {
    pub id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2c)]
pub struct ServerboundPlayRecipeBook {
    #[field(varint)]
    pub book_id: i32,
    pub book_open: bool,
    pub filter_active: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2f)]
pub struct ServerboundPlayResourcePackReceive {
    pub uuid: Uuid,
    #[field(varint)]
    pub result: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0b)]
pub struct ServerboundPlayTickEnd;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x34)]
pub struct ServerboundPlayUpdateCommandBlock {
    pub location: Position,
    pub command: String,
    #[field(varint)]
    pub mode: i32,
    pub flags: u8,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x35)]
pub struct ServerboundPlayUpdateCommandBlockMinecart {
    #[field(varint)]
    pub entity_id: i32,
    pub command: String,
    pub track_output: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x37)]
pub struct ServerboundPlayUpdateJigsawBlock {
    pub location: Position,
    pub name: String,
    pub target: String,
    pub pool: String,
    pub final_state: String,
    pub joint_type: String,
    #[field(varint)]
    pub selection_priority: i32,
    #[field(varint)]
    pub placement_priority: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x38)]
pub struct ServerboundPlayUpdateStructureBlock {
    pub location: Position,
    #[field(varint)]
    pub action: i32,
    #[field(varint)]
    pub mode: i32,
    pub name: String,
    pub offset_x: i8,
    pub offset_y: i8,
    pub offset_z: i8,
    pub size_x: i8,
    pub size_y: i8,
    pub size_z: i8,
    #[field(varint)]
    pub mirror: i32,
    #[field(varint)]
    pub rotation: i32,
    pub metadata: String,
    pub integrity: f32,
    #[field(varint)]
    pub seed: i32,
    pub flags: u8,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3d)]
pub struct ServerboundPlayUseItem {
    #[field(varint)]
    pub hand: i32,
    #[field(varint)]
    pub sequence: i32,
    pub rotation: Vec2f,
}

// -- Clientbound packets --

/// Inline data structure used by [`ClientboundPlayAdvancements`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayAdvancementsAdvancementmapping {
    pub key: String,
    pub value: Vec<u8>,
}

/// Inline data structure used by [`ClientboundPlayAdvancements`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayAdvancementsProgressmapping {
    pub key: String,
    #[field(length = "varint")]
    pub value: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x7b)]
pub struct ClientboundPlayAdvancements {
    pub reset: bool,
    #[field(length = "varint")]
    pub advancement_mapping: Vec<ClientboundPlayAdvancementsAdvancementmapping>,
    #[field(length = "varint")]
    pub identifiers: Vec<String>,
    #[field(length = "varint")]
    pub progress_mapping: Vec<ClientboundPlayAdvancementsProgressmapping>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x19)]
pub struct ClientboundPlayCustomPayload {
    pub channel: String,
    #[field(rest)]
    pub data: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1b)]
pub struct ClientboundPlayDebugSample {
    #[field(length = "varint")]
    pub sample: Vec<i64>,
    #[field(varint)]
    pub r#type: i32,
}

/// Inline data structure used by [`ClientboundPlayDeclareRecipes`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayDeclareRecipesRecipes {
    pub name: String,
    #[field(length = "varint")]
    pub items: Vec<i32>,
}

/// Inline data structure used by [`ClientboundPlayDeclareRecipes`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayDeclareRecipesStonecutterrecipes {
    pub input: Vec<u8>,
    pub slot_display: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x7e)]
pub struct ClientboundPlayDeclareRecipes {
    #[field(length = "varint")]
    pub recipes: Vec<ClientboundPlayDeclareRecipesRecipes>,
    #[field(length = "varint")]
    pub stone_cutter_recipes: Vec<ClientboundPlayDeclareRecipesStonecutterrecipes>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x27)]
pub struct ClientboundPlayKeepAlive {
    pub keep_alive_id: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1d)]
pub struct ClientboundPlayKickDisconnect {
    pub reason: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x37)]
pub struct ClientboundPlayPing {
    pub id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x38)]
pub struct ClientboundPlayPingResponse {
    pub id: i64,
}

/// Inline data structure used by [`ClientboundPlayRecipeBookAdd`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayRecipeBookAddEntries {
    pub recipe: Vec<u8>,
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x44)]
pub struct ClientboundPlayRecipeBookAdd {
    #[field(length = "varint")]
    pub entries: Vec<ClientboundPlayRecipeBookAddEntries>,
    pub replace: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x45)]
pub struct ClientboundPlayRecipeBookRemove {
    #[field(length = "varint")]
    pub recipe_ids: Vec<i32>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x46)]
pub struct ClientboundPlayRecipeBookSettings {
    pub crafting_gui_open: bool,
    pub crafting_filtering_craftable: bool,
    pub smelting_gui_open: bool,
    pub smelting_filtering_craftable: bool,
    pub blast_gui_open: bool,
    pub blast_filtering_craftable: bool,
    pub smoker_gui_open: bool,
    pub smoker_filtering_craftable: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x4f)]
pub struct ClientboundPlaySelectAdvancementTab {
    #[field(optional)]
    pub id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x50)]
pub struct ClientboundPlayServerData {
    pub motd: NbtCompound,
    #[field(optional)]
    pub icon_bytes: Option<Vec<u8>>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x78)]
pub struct ClientboundPlaySetTickingState {
    pub tick_rate: f32,
    pub is_frozen: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x6f)]
pub struct ClientboundPlaySoundEffect {
    pub sound: Vec<u8>,
    #[field(varint)]
    pub sound_category: i32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub volume: f32,
    pub pitch: f32,
    pub seed: i64,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x70)]
pub struct ClientboundPlayStartConfiguration;

/// Inline data structure used by [`ClientboundPlayStatistics`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayStatisticsEntries {
    #[field(varint)]
    pub category_id: i32,
    #[field(varint)]
    pub statistic_id: i32,
    #[field(varint)]
    pub value: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x04)]
pub struct ClientboundPlayStatistics {
    #[field(length = "varint")]
    pub entries: Vec<ClientboundPlayStatisticsEntries>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x79)]
pub struct ClientboundPlayStepTick {
    #[field(varint)]
    pub tick_steps: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x71)]
pub struct ClientboundPlayStopSound {
    pub flags: i8,
    pub source: Vec<u8>,
    pub sound: Vec<u8>,
}

/// Inline data structure used by [`ClientboundPlayTags`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayTagsTags {
    pub tag_type: String,
    pub tags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x7f)]
pub struct ClientboundPlayTags {
    #[field(length = "varint")]
    pub tags: Vec<ClientboundPlayTagsTags>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use basalt_types::{Encode as _, EncodedSize as _};

    #[test]
    fn serverbound_play_advancement_tab_roundtrip() {
        let original = ServerboundPlayAdvancementTab::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayAdvancementTab::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_configuration_acknowledged_roundtrip() {
        let original = ServerboundPlayConfigurationAcknowledged;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayConfigurationAcknowledged::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_custom_payload_roundtrip() {
        let original = ServerboundPlayCustomPayload::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayCustomPayload::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_debug_sample_subscription_roundtrip() {
        let original = ServerboundPlayDebugSampleSubscription::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayDebugSampleSubscription::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_displayed_recipe_roundtrip() {
        let original = ServerboundPlayDisplayedRecipe::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayDisplayedRecipe::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_edit_book_roundtrip() {
        let original = ServerboundPlayEditBook::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayEditBook::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_keep_alive_roundtrip() {
        let original = ServerboundPlayKeepAlive::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayKeepAlive::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_ping_request_roundtrip() {
        let original = ServerboundPlayPingRequest::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPingRequest::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_pong_roundtrip() {
        let original = ServerboundPlayPong::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPong::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_recipe_book_roundtrip() {
        let original = ServerboundPlayRecipeBook::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayRecipeBook::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_resource_pack_receive_roundtrip() {
        let original = ServerboundPlayResourcePackReceive::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayResourcePackReceive::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_tick_end_roundtrip() {
        let original = ServerboundPlayTickEnd;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayTickEnd::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_update_command_block_roundtrip() {
        let original = ServerboundPlayUpdateCommandBlock::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayUpdateCommandBlock::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_update_command_block_minecart_roundtrip() {
        let original = ServerboundPlayUpdateCommandBlockMinecart::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayUpdateCommandBlockMinecart::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_update_jigsaw_block_roundtrip() {
        let original = ServerboundPlayUpdateJigsawBlock::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayUpdateJigsawBlock::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_update_structure_block_roundtrip() {
        let original = ServerboundPlayUpdateStructureBlock::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayUpdateStructureBlock::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_use_item_roundtrip() {
        let original = ServerboundPlayUseItem::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayUseItem::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_advancements_roundtrip() {
        let original = ClientboundPlayAdvancements::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayAdvancements::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_custom_payload_roundtrip() {
        let original = ClientboundPlayCustomPayload::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayCustomPayload::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_debug_sample_roundtrip() {
        let original = ClientboundPlayDebugSample::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayDebugSample::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_declare_recipes_roundtrip() {
        let original = ClientboundPlayDeclareRecipes::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayDeclareRecipes::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_keep_alive_roundtrip() {
        let original = ClientboundPlayKeepAlive::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayKeepAlive::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_kick_disconnect_roundtrip() {
        let original = ClientboundPlayKickDisconnect::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayKickDisconnect::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_ping_roundtrip() {
        let original = ClientboundPlayPing::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPing::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_ping_response_roundtrip() {
        let original = ClientboundPlayPingResponse::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPingResponse::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_recipe_book_add_roundtrip() {
        let original = ClientboundPlayRecipeBookAdd::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayRecipeBookAdd::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_recipe_book_remove_roundtrip() {
        let original = ClientboundPlayRecipeBookRemove::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayRecipeBookRemove::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_recipe_book_settings_roundtrip() {
        let original = ClientboundPlayRecipeBookSettings::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayRecipeBookSettings::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_select_advancement_tab_roundtrip() {
        let original = ClientboundPlaySelectAdvancementTab::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySelectAdvancementTab::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_server_data_roundtrip() {
        let original = ClientboundPlayServerData::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayServerData::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_set_ticking_state_roundtrip() {
        let original = ClientboundPlaySetTickingState::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySetTickingState::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_sound_effect_roundtrip() {
        let original = ClientboundPlaySoundEffect::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySoundEffect::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_start_configuration_roundtrip() {
        let original = ClientboundPlayStartConfiguration;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayStartConfiguration::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_statistics_roundtrip() {
        let original = ClientboundPlayStatistics::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayStatistics::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_step_tick_roundtrip() {
        let original = ClientboundPlayStepTick::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayStepTick::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_stop_sound_roundtrip() {
        let original = ClientboundPlayStopSound::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayStopSound::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_tags_roundtrip() {
        let original = ClientboundPlayTags::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayTags::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }
}
