//! Play state — player packets.
//!
//! Auto-generated by `cargo xt codegen` from minecraft-data.
//! Do not edit manually — changes will be overwritten.

use basalt_derive::{Decode, Encode, EncodedSize, packet};
use basalt_types::{NbtCompound, Uuid};

// -- Serverbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x26)]
pub struct ServerboundPlayAbilities {
    pub flags: i8,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0a)]
pub struct ServerboundPlayClientCommand {
    #[field(varint)]
    pub action_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1f)]
pub struct ServerboundPlayFlying {
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1b)]
pub struct ServerboundPlayLockDifficulty {
    pub locked: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1e)]
pub struct ServerboundPlayLook {
    pub yaw: f32,
    pub pitch: f32,
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x29)]
pub struct ServerboundPlayPlayerInput {
    pub inputs: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2a)]
pub struct ServerboundPlayPlayerLoaded;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1c)]
pub struct ServerboundPlayPosition {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x1d)]
pub struct ServerboundPlayPositionLook {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x03)]
pub struct ServerboundPlaySetDifficulty {
    pub new_difficulty: u8,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3b)]
pub struct ServerboundPlaySpectate {
    pub target: Uuid,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x21)]
pub struct ServerboundPlaySteerBoat {
    pub left_paddle: bool,
    pub right_paddle: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x00)]
pub struct ServerboundPlayTeleportConfirm {
    #[field(varint)]
    pub teleport_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x20)]
pub struct ServerboundPlayVehicleMove {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub on_ground: bool,
}

// -- Clientbound packets --

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3a)]
pub struct ClientboundPlayAbilities {
    pub flags: i8,
    pub flying_speed: f32,
    pub walking_speed: f32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x57)]
pub struct ClientboundPlayCamera {
    #[field(varint)]
    pub camera_id: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3e)]
pub struct ClientboundPlayDeathCombatEvent {
    #[field(varint)]
    pub player_id: i32,
    pub message: NbtCompound,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x0b)]
pub struct ClientboundPlayDifficulty {
    pub difficulty: u8,
    pub difficulty_locked: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3c)]
pub struct ClientboundPlayEndCombatEvent {
    #[field(varint)]
    pub duration: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3d)]
pub struct ClientboundPlayEnterCombatEvent;

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x61)]
pub struct ClientboundPlayExperience {
    pub experience_bar: f32,
    #[field(varint)]
    pub level: i32,
    #[field(varint)]
    pub total_experience: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x41)]
pub struct ClientboundPlayFacePlayer {
    #[field(varint)]
    pub feet_eyes: i32,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub is_entity: bool,
    pub entity_id: Vec<u8>,
    pub entity_feet_eyes: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x23)]
pub struct ClientboundPlayGameStateChange {
    pub reason: u8,
    pub game_mode: f32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x2c)]
pub struct ClientboundPlayLogin {
    pub entity_id: i32,
    pub is_hardcore: bool,
    #[field(length = "varint")]
    pub world_names: Vec<String>,
    #[field(varint)]
    pub max_players: i32,
    #[field(varint)]
    pub view_distance: i32,
    #[field(varint)]
    pub simulation_distance: i32,
    pub reduced_debug_info: bool,
    pub enable_respawn_screen: bool,
    pub do_limited_crafting: bool,
    pub world_state: Vec<u8>,
    pub enforces_secure_chat: bool,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3b)]
pub struct ClientboundPlayPlayerChat {
    pub sender_uuid: Uuid,
    #[field(varint)]
    pub index: i32,
    #[field(optional)]
    pub signature: Option<Vec<u8>>,
    pub plain_message: String,
    pub timestamp: i64,
    pub salt: i64,
    pub previous_messages: Vec<u8>,
    #[field(optional)]
    pub unsigned_chat_content: Option<NbtCompound>,
    #[field(varint)]
    pub filter_type: i32,
    pub filter_type_mask: Vec<u8>,
    pub r#type: Vec<u8>,
    pub network_name: NbtCompound,
    #[field(optional)]
    pub network_target_name: Option<NbtCompound>,
}

/// Inline data structure used by [`ClientboundPlayPlayerInfo`].
#[derive(Debug, Clone, Default, PartialEq, Encode, Decode, EncodedSize)]
pub struct ClientboundPlayPlayerInfoData {
    pub uuid: Uuid,
    pub player: Vec<u8>,
    pub chat_session: Vec<u8>,
    pub gamemode: Vec<u8>,
    pub listed: Vec<u8>,
    pub latency: Vec<u8>,
    pub display_name: Vec<u8>,
    pub list_priority: Vec<u8>,
    pub show_hat: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x40)]
pub struct ClientboundPlayPlayerInfo {
    pub action: Vec<u8>,
    #[field(length = "varint")]
    pub data: Vec<ClientboundPlayPlayerInfoData>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x3f)]
pub struct ClientboundPlayPlayerRemove {
    #[field(length = "varint")]
    pub players: Vec<Uuid>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x43)]
pub struct ClientboundPlayPlayerRotation {
    pub yaw: f32,
    pub pitch: f32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x42)]
pub struct ClientboundPlayPosition {
    #[field(varint)]
    pub teleport_id: i32,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub dx: f64,
    pub dy: f64,
    pub dz: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub flags: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x4c)]
pub struct ClientboundPlayRespawn {
    pub world_state: Vec<u8>,
    pub copy_metadata: u8,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x69)]
pub struct ClientboundPlaySimulationDistance {
    #[field(varint)]
    pub distance: i32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x62)]
pub struct ClientboundPlayUpdateHealth {
    pub health: f32,
    #[field(varint)]
    pub food: i32,
    pub food_saturation: f32,
}

#[derive(Debug, Clone, Default, PartialEq)]
#[packet(id = 0x33)]
pub struct ClientboundPlayVehicleMove {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
}

#[cfg(test)]
mod tests {
    use super::*;
    use basalt_types::{Encode as _, EncodedSize as _};

    #[test]
    fn serverbound_play_abilities_roundtrip() {
        let original = ServerboundPlayAbilities::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayAbilities::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_client_command_roundtrip() {
        let original = ServerboundPlayClientCommand::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayClientCommand::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_flying_roundtrip() {
        let original = ServerboundPlayFlying::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayFlying::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_lock_difficulty_roundtrip() {
        let original = ServerboundPlayLockDifficulty::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayLockDifficulty::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_look_roundtrip() {
        let original = ServerboundPlayLook::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayLook::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_player_input_roundtrip() {
        let original = ServerboundPlayPlayerInput::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPlayerInput::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_player_loaded_roundtrip() {
        let original = ServerboundPlayPlayerLoaded;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPlayerLoaded::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_position_roundtrip() {
        let original = ServerboundPlayPosition::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPosition::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_position_look_roundtrip() {
        let original = ServerboundPlayPositionLook::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayPositionLook::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_set_difficulty_roundtrip() {
        let original = ServerboundPlaySetDifficulty::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySetDifficulty::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_spectate_roundtrip() {
        let original = ServerboundPlaySpectate::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySpectate::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_steer_boat_roundtrip() {
        let original = ServerboundPlaySteerBoat::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlaySteerBoat::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_teleport_confirm_roundtrip() {
        let original = ServerboundPlayTeleportConfirm::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayTeleportConfirm::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn serverbound_play_vehicle_move_roundtrip() {
        let original = ServerboundPlayVehicleMove::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ServerboundPlayVehicleMove::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_abilities_roundtrip() {
        let original = ClientboundPlayAbilities::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayAbilities::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_camera_roundtrip() {
        let original = ClientboundPlayCamera::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayCamera::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_death_combat_event_roundtrip() {
        let original = ClientboundPlayDeathCombatEvent::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayDeathCombatEvent::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_difficulty_roundtrip() {
        let original = ClientboundPlayDifficulty::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayDifficulty::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_end_combat_event_roundtrip() {
        let original = ClientboundPlayEndCombatEvent::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayEndCombatEvent::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_enter_combat_event_roundtrip() {
        let original = ClientboundPlayEnterCombatEvent;
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayEnterCombatEvent::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_experience_roundtrip() {
        let original = ClientboundPlayExperience::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayExperience::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_face_player_roundtrip() {
        let original = ClientboundPlayFacePlayer::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayFacePlayer::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_game_state_change_roundtrip() {
        let original = ClientboundPlayGameStateChange::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayGameStateChange::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_login_roundtrip() {
        let original = ClientboundPlayLogin::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayLogin::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_player_chat_roundtrip() {
        let original = ClientboundPlayPlayerChat::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPlayerChat::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_player_info_roundtrip() {
        let original = ClientboundPlayPlayerInfo::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPlayerInfo::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_player_remove_roundtrip() {
        let original = ClientboundPlayPlayerRemove::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPlayerRemove::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_player_rotation_roundtrip() {
        let original = ClientboundPlayPlayerRotation::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPlayerRotation::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_position_roundtrip() {
        let original = ClientboundPlayPosition::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayPosition::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_respawn_roundtrip() {
        let original = ClientboundPlayRespawn::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayRespawn::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_simulation_distance_roundtrip() {
        let original = ClientboundPlaySimulationDistance::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlaySimulationDistance::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_update_health_roundtrip() {
        let original = ClientboundPlayUpdateHealth::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayUpdateHealth::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }

    #[test]
    fn clientbound_play_vehicle_move_roundtrip() {
        let original = ClientboundPlayVehicleMove::default();
        let mut buf = Vec::with_capacity(original.encoded_size());
        original.encode(&mut buf).unwrap();
        assert_eq!(buf.len(), original.encoded_size());
        let mut cursor = buf.as_slice();
        let decoded = ClientboundPlayVehicleMove::decode(&mut cursor).unwrap();
        assert!(cursor.is_empty());
        assert_eq!(decoded, original);
    }
}
